6114 Lab2L Seredova_Alieva
itsecd/academic-fundamentals pull request #102
Opened 2024-04-13 13:09 UTC by SeredovaSophia

2024-04-15 14:22 UTC, Olga1140 requested changes
Отметила часть, которую надо доработать, в остальном все отлично)

2024-04-15 14:22 UTC, Olga1140 commented on article.tex
> +where S – minimum score value in the compatibility analysis;
Если в тексте встречаются параметры или переменные, их нужно выделять долларами. Сделайте так, чтобы "where" было в одной строке с формулой

2024-04-15 20:31 UTC, SeredovaSophia commented on article.tex
> +where S – minimum score value in the compatibility analysis;
Здравствуйте! Вот исправленный код:

`\end{Vmatrix}
\label{4}
\text {where} 
\end{equation}
$S$  – minimum score value in the compatibility analysis;\\
$x, y, z$  – vector coordinates.`

На всякий случай прикрепили файл article(1).tex

2024-04-16 07:52 UTC, Olga1140 approved these changes
Все хорошо, можете "where" вернуть на место, все, что хотела, я увидела. Молодцы)

2024-04-16 07:52 UTC, Olga1140 commented on article.tex
> +where S – minimum score value in the compatibility analysis;
Все хорошо, только перед "где" ставится запятая

2024-04-25 08:50 UTC, closed without merging