6114 Lab2L Чиндина Кулакова
itsecd/academic-fundamentals pull request #106
Opened 2024-04-16 19:03 UTC by lizoka-k

2024-04-16 19:06 UTC, lizoka-k commented
Добрый вечер, мы исправили код и создали новый pull request, чтобы не перегружать старый файлами

2024-04-18 15:18 UTC, Olga1140 requested changes
У меня вылезает ошибка при компиляции.
Если в тексте встречаются переменные, их нужно окружать долларами.
В тексте есть ссылка на картинку 1, сделайте ее автоматической.
У Вас все формулы легкие, сделайте что-то посложнее, в одной из них сделайте пояснение после слова "где" (в той же строке, что и формула).

2024-04-18 15:22 UTC, Olga1140 commented
Вы можете старый pull request тогда удалить? Или он Вам нужен? Не особо удобно, если у каждого несколько будет

2024-04-18 17:37 UTC, lizoka-k commented
Добрый вечер! Да, конечно, предыдущий pull request закрыли. Заменили сейчас старый tex файл на новый, исправленный. Новую формулу посложнее добавили в самый конец

2024-04-20 09:30 UTC, Olga1140 requested changes
1 Не все переменные и параметры окружены долларами. Это можете не доделывать, на ваше усмотрение. Просто запомните это на будущее.
2 Добавьте что-то с дробями, например. В задании написано, что каждая формула должна быть не очень легкая.
3 "где" можете вернуть на место, я увидела, как вы это сделали

Осталось немного) Жду исправленный вариант

2024-04-20 14:42 UTC, lizoka-k commented
Добрый вечер! Снизу добавили формулу посложнее в виде дроби и в предыдущей вернули "where" на место

2024-04-20 14:51 UTC, Olga1140 requested changes

2024-04-20 14:51 UTC, Olga1140 commented on spieman.tex
> +    T^{\mu}_{t} = \frac{\sum_{\upsilon=1}^\nu w^{\upsilon}_{t} \odot T^{\upsilon}_{t}}{\sum_{\upsilon=1}^\nu w^{\upsilon}_{t}}
Сделайте так, чтобы ограничения были не справа от суммы, а сверху и снизу

2024-04-20 14:59 UTC, lizoka-k commented
Прикрепили, теперь ограничения в сумме сверху и снизу

2024-04-20 15:07 UTC, Olga1140 approved these changes
Молодцы)

2024-04-26 07:11 UTC, closed without merging