6111 Lab2L Preobrazhenskiy Chekulaev
itsecd/academic-fundamentals pull request #109
Opened 2024-04-18 05:53 UTC by AndreyPreobrazhenskiy

2024-04-19 16:50 UTC, Olga1140 requested changes
Что конкретно нужно проверять? У Вас 3 файла latex. В папке много файлов, они все нужны?

2024-04-19 17:10 UTC, AndreyPreobrazhenskiy commented
Извините, это особенность примера форматирования с overleaf. Весь код находится в файле sample.teh

2024-04-19 19:20 UTC, Olga1140 requested changes
Не нашла списки.
Документ начинается с картинки, так задумано? Вы можете перекинуть их в документ? Просто обычно с титульника все начинается.
Не увидела формулы со словом "где ...". 
Если в тексте встречаются переменные или параметры, их надо выделять долларами, чтобы они отличались от текста.
Добавьте формулу посложнее, у вас 3 однотипные формулы.
Нет оглавления.

По поводу файлов в папке. Я говорила не про cls файл, а про второй tex, картинки, ... Они используются у вас? Если нет, то не нужно было их добавлять в эту папку

2024-04-19 19:20 UTC, Olga1140 commented on sample.tex
> +  \ p(S_i )=\frac{\sum_{j=i}^{i+k-1} p_j^+}{k}
Сделайте так, чтобы ограничения были не справа от \sum, а сверху и снизу

2024-04-22 15:33 UTC, AndreyPreobrazhenskiy commented
[BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS.zip](https://github.com/itsecd/academic-fundamentals/files/15065192/BIOMETRIC.AUTHENTICATION.BASED.ON.TOUCHSCREEN.SWIPE.PATTERNS.zip)
Исправленный архив (код в файле sample.tex, три фотографии .eps содержатся в файле), добавили оглавление.

2024-04-23 10:19 UTC, AndreyPreobrazhenskiy commented
Её заменить?

2024-04-23 16:39 UTC, AndreyPreobrazhenskiy commented
[Uploading BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS (1).zip
архив с исправленной формулой

2024-04-23 16:47 UTC, AndreyPreobrazhenskiy commented
[BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS done.zip](https://github.com/itsecd/academic-fundamentals/files/15080096/BIOMETRIC.AUTHENTICATION.BASED.ON.TOUCHSCREEN.SWIPE.PATTERNS.done.zip)
архив с изменённой формулой

2024-04-24 19:35 UTC, AndreyPreobrazhenskiy commented
[Uploading BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS da.zip…]()
исправленный вариант

2024-04-24 19:36 UTC, AndreyPreobrazhenskiy commented
[BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS da.zip](https://github.com/itsecd/academic-fundamentals/files/15099536/BIOMETRIC.AUTHENTICATION.BASED.ON.TOUCHSCREEN.SWIPE.PATTERNS.da.zip)
исправленный вариант

2024-04-27 04:40 UTC, Olga1140 requested changes
1 Сколько у вас списков?
2 Для чего нужна команда \text?

2024-04-27 06:40 UTC, AndreyPreobrazhenskiy commented
Один список, с помощью \text записывали в одну строчку с формулой условия с where.

2024-04-27 08:15 UTC, AndreyPreobrazhenskiy commented
Добавили нумерованный список
[BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS ed.zip](https://github.com/itsecd/academic-fundamentals/files/15137596/BIOMETRIC.AUTHENTICATION.BASED.ON.TOUCHSCREEN.SWIPE.PATTERNS.ed.zip)

2024-04-27 10:07 UTC, Olga1140 requested changes
Посмотрите, как вы используете \text в своих формулах. Везде ли там вообще нужна данная команда?

2024-04-27 10:16 UTC, AndreyPreobrazhenskiy commented
Просто если прописывать условие where не в \text, то оно выделяется курсивом и считается частью формулы.

2024-04-27 10:24 UTC, Olga1140 commented
Это я знаю. Посмотрите, что еще вы пишете с помощью этой команды

2024-04-27 10:27 UTC, AndreyPreobrazhenskiy commented
А можете подсказать в какой из формул?

2024-04-27 10:29 UTC, Olga1140 commented
В той, что посложнее

2024-04-27 10:30 UTC, Olga1140 commented
Вам нужно посмотреть, что записано с помощью этой команды. Решить, что нужно там записывать, а что нет. Что нужно записывать с помощью данной команды?

2024-04-27 10:33 UTC, AndreyPreobrazhenskiy commented
[BIOMETRIC AUTHENTICATION BASED ON TOUCHSCREEN SWIPE PATTERNS j.zip](https://github.com/itsecd/academic-fundamentals/files/15137874/BIOMETRIC.AUTHENTICATION.BASED.ON.TOUCHSCREEN.SWIPE.PATTERNS.j.zip)
Понял в чём проблема, само математическое условие прописал вне \text.

2024-04-27 10:34 UTC, Olga1140 commented
Вы можете сюда прислать просто ту часть текста, что вы поменяли? Я не хочу снова весь архив скачивать

2024-04-27 10:35 UTC, AndreyPreobrazhenskiy commented
![image](https://github.com/itsecd/academic-fundamentals/assets/164298315/5d1b76f1-7702-4176-bb42-c2ccc6edbd62)

2024-04-27 10:37 UTC, Olga1140 approved these changes

2024-05-16 04:17 UTC, closed without merging