6111 lab2L Chirkova Stepanova
itsecd/academic-fundamentals pull request #110
Opened 2024-04-18 06:18 UTC by AlexChirkova

2024-04-19 16:57 UTC, Olga1140 requested changes
У вас работает этот код? У меня нет

2024-04-22 11:51 UTC, AlexChirkova commented
[6111_Lab2L_Chirkova_Stepanova.zip](https://github.com/itsecd/academic-fundamentals/files/15062297/6111_Lab2L_Chirkova_Stepanova.zip)

Отдельно .tex файл почему-то не прикрепляется, но он есть в архиве.
![image](https://github.com/itsecd/academic-fundamentals/assets/162548434/d772d87a-af0b-402b-a757-3b177c1a1262)

2024-04-22 18:42 UTC, Olga1140 commented
Его и не надо прикреплять в комментарий. Файлы нужно прикреплять туда, куда вы уже прикрепили остальные

2024-04-22 18:45 UTC, Olga1140 commented
Я вставила все файлы из вашего архива, код не работает. Подумайте, почему так может быть

2024-04-24 11:48 UTC, AlexChirkova commented
Здравствуйте! Я прикрепила новые файлы. Извините, если это лишнее напоминание, я еще не до конца разобралась как работает гитхаб(

2024-04-24 22:07 UTC, Olga1140 requested changes
1 Лучше удалять файлы, которые больше не нужны
2 формулы достаточно простые, добавьте посложнее
3 Можете сделать ссылку на 1 таблицу?
4 Сделайте какие-то границы таблицы

2024-04-27 09:43 UTC, Olga1140 commented
Я не знаю, какие файлы мне надо скачать, у вас 3 архива и 2 tex файла

2024-04-27 09:53 UTC, AlexChirkova commented
Извините, видимо с телефона не выгрузился .tex файл. Сейчас 3 архива и 3 .tex, последние изменения в файлах, в названиях которых *(3).

2024-04-27 10:23 UTC, Olga1140 requested changes
1 У вас есть возможность удалять лишние файлы
2 Если в тексте встречаются переменные и параметры, их нужно окружать долларами
3 Сделайте так, чтобы в таблице текст был выровнен по левому краю или по середине
4 У вас много формул, но большинство из них простые, добавьте еще какую-то сложную формулу (она не должна быть похожа на те, что у вас уже есть)

2024-04-27 10:23 UTC, Olga1140 commented on lab-2/main(2).tex
> +f(x)=max(0,x) \label{eq2}
max должен быть написан не курсивым

2024-04-27 10:23 UTC, Olga1140 commented on lab-2/main(2).tex
> +f (x) = ln(1 + e^x) \label{eq3}
Аналогично предыдущему комментарию

2024-04-27 10:23 UTC, Olga1140 commented on lab-2/main(2).tex
> +    where & $m_{t} = m_{t}/ (1-b^t_{1}) $ \\
Скобки маленькие для выражения, находящегося в скобках
Добавьте "где..." в строку с самой формулой

2024-04-29 07:38 UTC, Olga1140 commented on lab-2/main(2).tex
> +    where & $m_{t} = m_{t}/ (1-b^t_{1}) $ \\
Почему вы формулу таблицей вводите. Вы можете систему написать, для этого есть окружения

2024-04-29 07:40 UTC, Olga1140 commented
Из того, что я до этого писала, не выполнен 2 пункт

Остальное зачтено. Доделайте последние замечания

2024-05-03 04:48 UTC, Olga1140 approved these changes

2024-05-16 04:18 UTC, closed without merging