6111 Lab2L Абдулханов Пупырев
itsecd/academic-fundamentals pull request #111
Opened 2024-04-18 06:33 UTC by Rovver52

2024-04-20 08:25 UTC, Olga1140 requested changes
1 Автор 1, автор 2, автор 3. Наверное, там должны быть фамилии.
2 У вас странно сделан список. Зачем для каждого пункта свой список? У вас в задании написано, что списков должно быть несколько, я увидела только один.
3 Добавьте еще формулу какую-нибудь. У вас формулы почти одинаковые.
4 В одной формуле должно быть пояснение, добавьте его в ту строку, где находится сама формула.

Все остальное хорошо, доделывайте и присылайте

2024-05-01 09:42 UTC, Rovver52 commented
[Tau - Lab Report Template (1).zip](https://github.com/itsecd/academic-fundamentals/files/15175957/Tau.-.Lab.Report.Template.1.zip)

2024-05-01 10:00 UTC, Rovver52 commented
А насчет вашего 4 пункта, там же 1 пояснение после третьей формулы объясняет все 3 формулы выше, там не нужно дополнительное пояснение

2024-05-04 18:13 UTC, Olga1140 commented
Вы добавили не очень сложную формулу.
А насчет 4 пункта, я попросила добавить пояснение в строку с самой формулой. Сделайте это, пожалуйста
А вы применяли второй cls файл? У вас в задании написано про это

2024-05-04 20:39 UTC, Rovver52 commented
Извините, я не совсем понимаю. Мне сделать для (1) формулы пояснение типа where...? 
Как здесь
![image](https://github.com/itsecd/academic-fundamentals/assets/164315321/f03447ad-019c-48f0-afa2-7a21f3b85c37)

2024-05-05 17:34 UTC, Rovver52 commented
исправил и сделал в разных cls
[Tau - Lab Report Template (2).zip](https://github.com/itsecd/academic-fundamentals/files/15213886/Tau.-.Lab.Report.Template.2.zip)
[Rho Class - Academic Article Template.zip](https://github.com/itsecd/academic-fundamentals/files/15213887/Rho.Class.-.Academic.Article.Template.zip)

2024-05-06 15:22 UTC, Olga1140 commented
Получается, что для каждого шаблона надо создавать все заново. Попробуйте просто добавить строки для переключения стиля в тот файл, который у вас уже был, просто лишнее закомментируйте, так вы сможете переключать шаблон за несколько движений

2024-05-06 15:24 UTC, Olga1140 commented
Все остальное хорошо, доделайте, и я вам зачту работу

2024-05-06 15:37 UTC, Rovver52 commented
![image](https://github.com/itsecd/academic-fundamentals/assets/164315321/44858063-d5e2-4984-81e2-8ae0fd20e6ef)
Исправил

2024-05-06 15:40 UTC, Olga1140 commented
Какие-то команды свойственны конкретному cls файлу, наверное, у вас проблемы с этим

2024-05-06 15:41 UTC, Rovver52 commented
а, да, вылезли, не заметил. Мне получается все равно нужно переделывать где-то код и также комментировать в зависимости от стиля?

2024-05-06 15:48 UTC, Olga1140 commented
Ну какие-то вещи да, придется комментировать. Для удобства можно рядом с командами отмечать, какие для какого стиля. Это лучше, чем создавать кучу отдельных файлов

2024-05-06 16:20 UTC, Rovver52 commented
[Using the tau LaTeXclass to write an academic article or lab report (3).zip](https://github.com/itsecd/academic-fundamentals/files/15223451/Using.the.tau.LaTeXclass.to.write.an.academic.article.or.lab.report.3.zip)
исправил

2024-05-06 16:26 UTC, Olga1140 commented
Какие строки надо раскомментировать, чтобы на первый стиль переключиться?

2024-05-06 16:28 UTC, Olga1140 commented
Прям по строчкам можете написать? Что надо включить, а что выключить

2024-05-06 16:44 UTC, Rovver52 commented
22 23 24 55-96

2024-05-06 16:48 UTC, Olga1140 commented
Все, зачтено

2024-05-06 16:49 UTC, Olga1140 approved these changes

2024-05-16 04:18 UTC, closed without merging