6112 Lab2L Вичурин Бабаев
itsecd/academic-fundamentals pull request #114
Opened 2024-04-18 07:59 UTC by VichurinNik

2024-04-20 08:34 UTC, Olga1140 requested changes
1 3 пункт задания не выполнен.
2 Если в тексте встречаются переменные или параметры, их надо выделять долларами, чтобы они отличались от текста.
3 Пояснение к формуле добавьте в ту строку, в которой находится сама формула.
4 Нет оглавления

2024-04-20 08:40 UTC, Olga1140 requested changes
Забыла в прошлом отзыве написать этот комментарий

2024-04-20 08:40 UTC, Olga1140 commented on main.tex
> +P(y_i)=\frac{e^Y_i}{\sum^c_i e^y_i}
Сделайте так, чтобы ограничения находились не справа от \sum, а сверху и снизу

2024-04-21 11:53 UTC, VichurinNik commented on main.tex
> +P(y_i)=\frac{e^Y_i}{\sum^c_i e^y_i}
Здравствуйте,переделали

2024-04-22 08:32 UTC, Olga1140 commented
Из того, что я писала, 3 и 4 пункты увидела, 2 не везде. Остальное не переделали

2024-04-22 15:01 UTC, VichurinNik commented
Я исправил 2 пункт и сделал ограничения сверху и снизу, но я не понимаю как из шаблона сделать свой текст ,мне получается надо там все оставить поменять только текст в .txt и добавить свои рисунки?

2024-04-22 19:09 UTC, Olga1140 commented
Проверьте еще раз ограничения. У меня они остались на старом месте.
Вам не нужно из шаблона делать свой текст, вам к своему тексту надо применить стиль. Надеюсь, я правильно поняла Ваш вопрос.

Ненужные файлы удаляйте, чтобы я понимала, что мне надо скачивать для проверки

2024-04-23 16:31 UTC, VichurinNik commented
Ну я сделал как вы сказали применил стили, а по поводу ограничений. В pdf они стоят сверху и снизу, если вы говорили про код, то я посмотрел у других кто сдал,у них ограничения написаны так же.

2024-04-24 19:20 UTC, Olga1140 commented
Теперь ограничения стоят там, где надо. В прошлом варианте tex файл компилировал не так.
Вопрос по стилю остается открытым. Как вы его применяете?

2024-04-24 20:00 UTC, VichurinNik commented
Я беру файлы cls из шаблона и вставляю в свой проект

2024-04-24 22:09 UTC, Olga1140 commented
У вас при этом стиль меняется? В пдф

2024-04-25 07:32 UTC, VichurinNik commented
Да,меняется

2024-04-27 06:19 UTC, Olga1140 commented
То есть, до этого он все таки не менялся? Теперь добавьте второй стиль. В этом же tex файле напишите строки для переключения стиля, для старого стиля строки нужно закоментировать.

2024-04-27 14:41 UTC, VichurinNik commented
Я сделал как вы сказали, старую строку со стилем закоментил, новую написал

2024-04-29 06:54 UTC, Olga1140 commented
Прочитайте внимательно 3 пункт задания

2024-05-03 04:59 UTC, Olga1140 commented
В третьем задании написано, что надо выбрать cls файл, а потом переключить его на другой cls файл. Какие cls файлы вы использовали? Я увидела только acmart

2024-05-03 10:45 UTC, VichurinNik commented
Понял, теперь я применил acmart.cls и потом biometrika.cls

2024-05-05 10:46 UTC, Olga1140 approved these changes
Зачтено

2024-05-16 04:18 UTC, closed without merging