6112 Lab2L Мифтяхов Фоменко
itsecd/academic-fundamentals pull request #122
Opened 2024-04-19 15:49 UTC by TimurMif

2024-04-20 09:34 UTC, Olga1140 requested changes
Вы видели сообщение в дискорде про zip-архив?

2024-04-20 12:12 UTC, Olga1140 requested changes
1 Не выполнен 3 пункт задания
2 Нет оглавления
3 Заголовки должны нумероваться автоматически
4 Если в тексте встречаются переменные или параметры, их надо выделять долларами, чтобы они отличались от текста
5 Латех показывает ошибки, у вас они возникают?
6 Формулы хорошие, только сделайте так, чтобы в 4 формуле ограничения были не справа от суммы, а сверху и снизу

2024-04-22 16:55 UTC, TimurMif commented
Пункты исправили.Виктор Андреевич, первую часть 2 лабораторной работы принял у нас без оглавления, поэтому мы Latex делали без оглавления.У нас и не было оглавления в первоначальном файле.

2024-04-23 10:18 UTC, Olga1140 commented
Оглавление было в задании, поэтому сделать вы его должны были.
В архиве 2 папки, в каждой есть tex файл. мне какой надо открывать?

2024-04-23 10:24 UTC, TimurMif commented
Второй Tex файл

2024-04-24 16:25 UTC, TimurMif commented
Мы добавили оглавление, но красное выделение на формулах исправить нам не удалось, уже все перепробовали

2024-04-24 18:41 UTC, Olga1140 commented
Зачем вам несколько tex файлов? Вы можете убрать лишнее? Какую функцию второй выполняет? Это стиль другой?

2024-04-25 04:40 UTC, TimurMif commented
Виктор  Андреевич нам писал в дискорде:„Важное замечание: когда отправляете на проверку латеховскую лабу, то у вас должно быть два файла: собственно файл .tex и zip-архив, в котором есть все файлы для корректного построения pdf, включая сам ваш pdf. В zip-архиве таким образом может лежать и ещё одна копия tex-файла. “

2024-04-27 05:43 UTC, Olga1140 commented
Я видела это сообщение. Первый tex файл должен быть на github, а в zip архиве может лежать его копия. Не нужно создавать одинаковые по содержанию файлы, это затрудняет проверку. Если я буду у каждой группы искать нужный файл, уйдет много времени, вы понимаете это? Уберите лишнее

2024-05-05 07:43 UTC, Olga1140 commented
Вот смотрите, я открываю ваши файлы, там я хочу видеть tex файл и zip архив, в котором находятся все файлы, которые нужны для нормальной компиляции. Ничего другого там быть не должно, не нужно создавать по несколько непонятных папок. Прежде чем что-то отправлять преподавателю, проверяйте, пожалуйста, что именно вы отправляете

2024-05-08 07:51 UTC, TimurMif commented
Высылаю вам zip файл со статьей и 2 pdf файла, в которых мы применили 2 стиля

2024-05-08 18:34 UTC, Olga1140 commented
Проверьте, тот ли архив вы мне прислали

2024-05-10 06:09 UTC, TimurMif commented
Архив точно тот,я его открыл, там наш файл main.tex и фотографии из статьи

2024-05-16 04:18 UTC, closed without merging