6111 Lab2L Panakshin Milekhin
itsecd/academic-fundamentals pull request #123
Opened 2024-04-20 09:42 UTC by AndreyPanakshin

2024-04-20 11:31 UTC, Olga1140 requested changes
Я увидела 2 tex файла, как я поняла, sample-acmsmall-biblatex.tex является примером с сайта, sample-acmsmall.tex - ваш. Вот ваш не запускается. В архив не нужно добавлять лишние файлы

2024-04-22 14:33 UTC, AndreyPanakshin commented
[lab2L.zip](https://github.com/itsecd/academic-fundamentals/files/15064456/lab2L.zip)
[sample-acmsmall (2).txt](https://github.com/itsecd/academic-fundamentals/files/15064489/sample-acmsmall.2.txt)
Здравствуйте,спасибо,убрали из zip файла лишние документы,на всякий случай прикрепляю переформатированный tex файл в txt,(т.к. мы проверяли,на разных компьютерах tex открывается)

2024-04-22 19:03 UTC, Olga1140 requested changes
1 Нет оглавления
2 Если в тексте находятся переменные и параметры, их надо выделять долларами, чтобы они отличались от остального текста

2024-04-23 16:55 UTC, AndreyPanakshin commented
[lab2L (1).zip](https://github.com/itsecd/academic-fundamentals/files/15080207/lab2L.1.zip)
Добрый вечер,спасибо,все исправили,отправляю zip с измененными файлами tex и pdf,на всякий случай в архиве также присутствует txt файл,если вдруг у вас не откроется tex.

2024-04-24 19:04 UTC, AndreyPanakshin commented on sample-acmsmall (2).tex
> +\frac{}{}
это как пример из документа скопировали,вставили случайно,видимо забыли удалить,надо исправить это в файле?

2024-04-24 19:06 UTC, Olga1140 commented on sample-acmsmall (2).tex
> +\frac{}{}
А в каком файле?

2024-04-24 19:09 UTC, AndreyPanakshin commented on sample-acmsmall (2).tex
> +\frac{}{}
взяли из документа с примерами функций,который был прикреплен на гит хабе,видимо,вставили лишний раз в наш tex файл .Оттуда его надо удалить и отправить вам исправленный вариант?

2024-04-24 19:09 UTC, Olga1140 commented on sample-acmsmall (2).tex
> +\frac{}{}
В каком документе вы это взяли?

2024-04-24 19:10 UTC, Olga1140 commented on sample-acmsmall (2).tex
> +\frac{}{}
Нет, просто лучше проверять, что вы отправляете

2024-04-24 19:10 UTC, Olga1140 approved these changes

2024-04-24 19:12 UTC, AndreyPanakshin commented on sample-acmsmall (2).tex
> +\frac{}{}
Взяли из документа lecture-latex.tex

2024-04-24 19:14 UTC, Olga1140 commented on sample-acmsmall (2).tex
> +\frac{}{}
Я поняла, мы сообщения одновременно отправили. Я вам зачла

2024-05-16 04:18 UTC, closed without merging