6114 Lab2L Носов Киселев
itsecd/academic-fundamentals pull request #125
Opened 2024-04-20 17:35 UTC by Dester

2024-04-20 18:11 UTC, Olga1140 requested changes
Добрый вечер
1 Параметры и переменные нужно всегда окружать долларами, чтобы они отличались от остального текста.
2 Формулы отличные, молодцы! В коде только написала 2 комментария.

2024-04-20 18:11 UTC, Olga1140 commented on main.tex
> +where $N_{y_i}$ is the number of proposals with the same label;
Нужно "где..." с небольшим объяснением перенести в ту строку, где находится сама формула.

2024-04-20 18:11 UTC, Olga1140 commented on main.tex
> +L_{z_i}=\frac{-1}{N_{y_i}-1}\sum^N_{j=1, j\neq{i}}I{y_i=y_j}log\frac{exp(z_l z_k/t)}{\sum^N_{k=1}exp(z_l z_k/t)}, \label{2}
Сделайте так, чтобы ограничения указывались не справа от суммы, а сверху и снизу

2024-04-20 19:55 UTC, Dester commented
файл с исправления, файл main.tex также был обновлён:
[laba 2 latex new.zip](https://github.com/itsecd/academic-fundamentals/files/15049534/laba.2.latex.new.zip)

2024-04-21 05:30 UTC, Olga1140 approved these changes
Можете вернуть "где..." на старое место. Работа зачтена

2024-04-21 05:30 UTC, Olga1140 commented on main.tex
> +L_{z_i}=\frac{-1}{N_{y_i}-1}\sum^N_{j=1, j\neq{i}}I{y_i=y_j}log\frac{exp(z_l z_k/t)}{\sum\limits^N_{k=1}exp(z_l z_k/t)}, \label{2} \text{where } N_{y_i} \text{ is the number}
Можно было N просто в доллары взять

2024-04-25 08:25 UTC, closed without merging