6113 Lab2L Svyatkovskaya Belov
itsecd/academic-fundamentals pull request #127
Opened 2024-04-21 18:15 UTC by freegotohell

2024-04-22 12:41 UTC, Olga1140 requested changes
Посмотрите, в каком виде вам сказали прикреплять файлы для 2 лабы

2024-04-24 21:01 UTC, Olga1140 requested changes
У вас достаточно однотипные формулы. Добавьте что-то еще

2024-04-29 05:54 UTC, freegotohell commented on main1.tex
> +    \frac{t^i_\nu-\nu p f^i \times \lambda_W}{i - \nu p f^i}, &\text{$W_i=0$, $I^i_{mean} \ge 128$}\\
заменить \frac на \dfraс в 41 и 42 строках

2024-04-29 05:55 UTC, freegotohell commented on main1.tex
> +    \frac{t^i_\nu-\nu p f^i \times \lambda_W}{i - \nu p f^i}, &\text{$W_i=0$, $I^i_{mean} \ge 128$}\\
заменить \frac на \dfrac в 41 и 42 строках

2024-04-29 06:39 UTC, freegotohell commented on main1.tex
> +\begin{equation}
\begin{equation}
\label{f3}
  \prod _{LM}\left ( D,g(D)) \right )=\frac{1}{nr}\cdot \sum_{i=1}^{n}\sum_{j=1}^{r}\frac{\left | \bar{R}(j)) \right |  -1}{\left | A_{j} \right | -1}
\end{equation}

2024-04-29 11:30 UTC, Olga1140 approved these changes

2024-04-29 11:30 UTC, Olga1140 commented on main1.tex
> +    \frac{t^i_\nu-\nu p f^i \times \lambda_W}{i - \nu p f^i}, &\text{$W_i=0$, $I^i_{mean} \ge 128$}\\
Лучше \cfrac, в этом случае у вас 2 и 3 строка не будут сливаться

2024-05-08 06:34 UTC, closed without merging