6111 Lab2L Шелашников Штенгауэр
itsecd/academic-fundamentals pull request #128
Opened 2024-04-21 19:11 UTC by Gladobedod

2024-04-27 04:08 UTC, Olga1140 commented
У вас 4 zip архива по второй лабе. Мне каждый надо скачать?

2024-04-27 07:02 UTC, Gladobedod commented
Извините, пожалуйста, с трудом разобрался как удалять файлы. Теперь, вроде бы, навёл порядок.

2024-04-27 09:46 UTC, Olga1140 commented
Теперь 2 архива. Оба нужны?

2024-04-27 16:04 UTC, Gladobedod commented
Да, один архив - работа с начальным шаблоном, другой - та же работа с использованием другого cls файла

2024-04-29 06:58 UTC, Olga1140 commented
Вам нужно их объединить. Сделайте один архив с нужными файлами для ваших шаблонов. Tex файл должен быть один. Добавьте строки для переключения стилей. Для одного из них строки закомментируйте, чтобы я смогла переключить стиль за пару действий

2024-05-03 19:25 UTC, Gladobedod commented
Здравствуйте! Всё сделал.

2024-05-05 13:03 UTC, Olga1140 requested changes
1 Не нашла маркированный список
2 Поставьте границы какие-нибудь у таблицы (В любом количестве)
3 В одной формуле добавьте "где..." в строку с самой формулой

2024-05-05 13:03 UTC, Olga1140 commented on sample-acmtog.tex
> +A = \frac{\frac{TP+TN}{FPR+FN}}{TN+FP+TP+FN}
Сделайте так, чтобы числитель и знаменатель не уменьшались (Сделайте это в шаблоне acmart)

2024-05-07 10:51 UTC, Olga1140 commented on sample-acmtog.tex
> +D_s =  \{\ x_n y_n\}\ ; \{\ n = 1,2,3...\}\ \quad \text{Where } x \text{ represents executable}
Отлично, только можно было сделать легче: внутри команды \text взять x в доллары

2024-05-07 10:51 UTC, Olga1140 commented on sample-acmtog.tex
> +A = \frac{\frac{TP+TN}{FPR+FN}}{TN+FP+TP+FN}
Это не выполнено

2024-05-07 10:57 UTC, Olga1140 requested changes
Исправляйте последние замечания

2024-05-07 10:57 UTC, Olga1140 commented on sample-acmtog.tex
> +F1 - score= 2 \int \frac{P*R}{P+R}dP
Добавьте какие-нибудь пределы интегрирования, а то я посмотрела, какие-то не сильно сложные формулы у вас

2024-05-09 06:43 UTC, Gladobedod commented
Здравствуйте! Добавил пределы интергирования, исправил "уменьшение" формул, учел Ваше замечание по поводу того, что в формуле с "where" можно было 'x' просто взять в доллары.

2024-05-09 13:48 UTC, Olga1140 commented
Добрый день, к сожалению, вы сделали это слишком поздно, вам нужно было исправить 2 маленьких замечания и все.

новый дедлайн - 9 мая. До этой даты можно отправлять в PR и вносить правки

Сегодня уже не "до этой даты"

2024-05-16 04:18 UTC, closed without merging