6114 Lab2L Попов Никишин
itsecd/academic-fundamentals pull request #131
Opened 2024-04-23 12:55 UTC by Vantany

2024-04-27 03:27 UTC, Olga1140 requested changes
1 Нет отдельного тех файла
2 Не выполнен 3 пункт
3 Недостаточное количество списков
4 Для чего используется [label=\arabic*.]?
5 Поставьте границы таблицы слева и справа
6 Посмотрите, что вам написали в задании про формулы

2024-05-01 08:02 UTC, Vantany commented
Внесены изменения:
- добавлен tex файл
- у таблицы сделаны края
- добавлены усложненные формулы
- добавлены недостающие списки

2024-05-03 06:06 UTC, Olga1140 requested changes
1 Все еще не выполнен пункт 3
2 В прошлом комментарии я вам задала вопрос. Вы на него не ответили

2024-05-03 06:06 UTC, Olga1140 commented on lab-2/main.tex
> +    \lambda_{coord} = \sum_{i = 0}^{s^{2}} \sum_{j = 0}^{M} (\sqrt{w_{i}} - \sqrt{w_{j}})^{2}
Скобки маленькие для выражения в скобках

2024-05-03 06:06 UTC, Olga1140 commented on lab-2/main.tex
> +    0, &\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
Сделайте так, чтобы числитель и знаменатель дроби не уменьшались

2024-05-03 06:06 UTC, Olga1140 commented on lab-2/main.tex
> ++ \lambda _ {cord} \sum _ {i=0}^ {s}  \sum _ {i=0}^ {2}  10^ {b} [( \sqrt {w_ {i}}  -  \sqrt {w_ {i})^ {2}+(\sqrt {h_ {i}}-\sqrt {h_ {i}})^ {2}}
Номер формулы поставился слева, а не справа, а также вылезла ошибка
Над чем находится первая крышечка?
Скобки маленькие

2024-05-06 12:13 UTC, Vantany commented
Учтены вышеперечисленные замечания, отвечая на заданный вопрос про использование [label=\arabic*.], эта строка была изначально в темплейте.

2024-05-07 08:43 UTC, Olga1140 requested changes
Объедините два tex файла в один. Добавьте строки для переключения шаблона, строки для первого шаблона закомментируйте. проверьте, нет ли ошибок при компиляции

2024-05-07 08:43 UTC, Olga1140 commented on lab-2/V1.tex
> +    \lambda_{coord} = \sum_{i = 0}^{s^{2}} \sum_{j = 0}^{M} \Biggl(\sqrt{w_{i}} - \sqrt{w_{j}}\Biggl)^{2}
Сделайте так, чтобы высота скобок подбиралась автоматически

2024-05-07 08:43 UTC, Olga1140 commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
Вы сделали что-то странное

2024-05-07 08:43 UTC, Olga1140 commented on lab-2/V1.tex
> +     \lambda _ {coord} \sum _ {i=0}^ {s} \sum _ {i=0}^ {B} 1_ {ij}^ {obj} \Biggl[  \Biggl(x_ {i}-\widehat {}x_ {i}\Biggl)^ {2}  +  \Biggl(y_ {i}-\widehat {y}i\Biggl)^ {2} \Biggl]
Над чем находится первая крышечка?

2024-05-07 13:21 UTC, Vantany commented on lab-2/V1.tex
> +     \lambda _ {coord} \sum _ {i=0}^ {s} \sum _ {i=0}^ {B} 1_ {ij}^ {obj} \Biggl[  \Biggl(x_ {i}-\widehat {}x_ {i}\Biggl)^ {2}  +  \Biggl(y_ {i}-\widehat {y}i\Biggl)^ {2} \Biggl]
да, не заметил, простите

2024-05-07 13:25 UTC, Vantany commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
нашел ошибку, заменил \frac на \dfrac, теперь все выглядит одинаково

2024-05-07 13:40 UTC, Vantany commented
Исправил ошибки и сделал как вы сказали, простите, что сразу не до конца понял

2024-05-07 13:50 UTC, Olga1140 commented on lab-2/V1.tex
> +    \lambda_{coord} = \sum_{i = 0}^{s^{2}} \sum_{j = 0}^{M} \Biggl(\sqrt{w_{i}} - \sqrt{w_{j}}\Biggl)^{2}
они будут нормальными, они автоматически подбираются нужной высоты

2024-05-07 13:51 UTC, Olga1140 commented
Какой архив скачивать? У вас их много

2024-05-07 13:52 UTC, Vantany commented on lab-2/V1.tex
> +    \lambda_{coord} = \sum_{i = 0}^{s^{2}} \sum_{j = 0}^{M} \Biggl(\sqrt{w_{i}} - \sqrt{w_{j}}\Biggl)^{2}
ну я в последнем коммите поставил так, хорошо

2024-05-07 13:53 UTC, Vantany commented
с последнего коммита, который называется "update"

2024-05-07 14:13 UTC, Olga1140 commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
Для чего нужна команда \text?

2024-05-07 14:16 UTC, Olga1140 commented
У вас ошибки вылезают?
Одно из заданий по формулам все еще не выполнено. Вам сказали написать в одной формуле пояснение. Можете написать его в системе

2024-05-07 14:17 UTC, Vantany commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
честно говоря, наверно не нужна, но из источника из которого я брал пример она была, поэтому я решил оставить на всякий случай

2024-05-07 14:18 UTC, Vantany commented
нет, ошибки не вылезают, все проверил несколько раз, да, сейчас изменю на гитхабе и дополню формулу

2024-05-07 14:18 UTC, Vantany commented
я тогда только main.tex поменяю?

2024-05-07 14:20 UTC, Olga1140 commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
Вы все лабы так делаете? Мы не знаем что это, но пусть будет. У вас как минимум есть интернет, вы там что-то смотреть можете. Или как минимум вы просто могли удалить это и посмотреть, что будет

2024-05-07 14:28 UTC, Vantany commented
![image](https://github.com/itsecd/academic-fundamentals/assets/119051119/27da5fdc-31e0-4454-b463-ebf28e73e2f4)

2024-05-07 14:28 UTC, Vantany commented
изменение в системе тоже внес

2024-05-07 14:29 UTC, Vantany commented on lab-2/V1.tex
> +    0, &\Large\text{$\frac{g1(1-r^n )}{(1-r)}$}\\
Надеюсь научимся

2024-05-07 14:29 UTC, Olga1140 commented
Теперь Вы можете сказать, для чего команда \text?

2024-05-07 14:30 UTC, Olga1140 commented
Но я хотела увидеть скрин всего окна

2024-05-07 14:30 UTC, Vantany commented
Ну чтобы текст к формуле добавлять

2024-05-07 14:30 UTC, Vantany commented
![image](https://github.com/itsecd/academic-fundamentals/assets/119051119/363a79b7-8c81-4488-9e99-4b739b570d99)

2024-05-07 14:32 UTC, Olga1140 commented
Про \text хорошо, надеюсь
Про скрин, Вы видите что-то красное? Это ошибки

2024-05-07 14:38 UTC, Vantany commented
Да, но они же не мешают компиляции?

2024-05-07 14:38 UTC, Vantany commented
![image](https://github.com/itsecd/academic-fundamentals/assets/119051119/02961b2d-6d8d-409e-96e2-15af3b1dbe94)

2024-05-07 15:35 UTC, Vantany commented
я понял, прочитал про эти ошибки, она заключалась в том, что я забыл подключить соответствующие пакеты

2024-05-07 19:02 UTC, Olga1140 commented
Отлично. Вы мне пришлете обновленный архив?

2024-05-08 06:48 UTC, Vantany commented
Простите за задержку, вчера уже не увидел

2024-05-08 18:04 UTC, Olga1140 commented
У вас раньше, вроде, не было ошибок в шаблоне volcanica-template. Теперь есть. Проверьте, возможно, эти шаблоны требуют, чтобы вы написали авторов, название, еще что-то

2024-05-09 14:41 UTC, Vantany commented
да, где объявления самого шаблона я пока искал ошибки удалил [draft, {\secondLanguage}, english] у \documentclass

2024-05-09 15:00 UTC, Olga1140 commented
Вы прислали изменения поздно, но я посмотрела. Вы не только это удалили, там еще несколько строк не хватает. Вы проверяйте хоть, вылезают ошибки или нет. Вы и в другом стиле ошибки не исправили. Как я уже писала, некоторые шаблоны требуют написания авторов, названия работы и т.д.

2024-05-09 15:04 UTC, Vantany commented
просто все же работает согласно заданию

2024-05-09 15:12 UTC, Olga1140 commented
Уже ничего не надо делать, напомню, что первый дедлайн у вас стоял 25 апреля, после этого вам продлили сдачу на 2 недели, но вы и в них не уложились, а могли, если бы сразу выполняли все мои замечания, а не по частям. По поводу того, что все работает согласно заданию, я уже писала вам, что другой компилятор не будет компилировать код, если в нем есть ошибки, а у вас они есть

2024-05-16 04:18 UTC, closed without merging