6114 Lab2L Ченцов Морозов
itsecd/academic-fundamentals pull request #132
Opened 2024-04-23 18:40 UTC by Deemeed

2024-04-24 21:07 UTC, Olga1140 requested changes
1 Если в тексте встречаются переменные или параметры, их надо выделять долларами, чтобы они отличались от остального текста
2 Достаточно легкие формулы, добавьте еще что-то

Все остальное неплохо

2024-04-24 21:07 UTC, Olga1140 commented on sample-acmlarge.tex
> +where Precision - defined in Equation 1\par
Добавьте "где..." в строку с самой формулой

2024-04-29 14:18 UTC, Deemeed commented
Обновили измененные файлы

2024-05-03 04:32 UTC, Olga1140 commented
acmart_2.cls это второй стиль?
1 пункт из моего прошлого комментария не везде выполнен

2024-05-03 15:50 UTC, Deemeed commented
Да, acmart_2.cls - это второй стиль.
Постарался по 1-му пункту выделить максимально, вроде все нашел

2024-05-05 12:49 UTC, Olga1140 commented
У вас что-то меняется, когда вы применяете acmart_2.cls?

2024-05-05 13:37 UTC, Deemeed commented
Да, у acmart там есть два шаблона, один large и один ещё какой-то, и это два разных шаблона я отправил

2024-05-05 13:48 UTC, Olga1140 commented
У меня вообще ничего не меняется

2024-05-05 17:51 UTC, Deemeed commented
Добавили совершенно другой стиль. Всё меняется и запускается

2024-05-06 17:34 UTC, Olga1140 requested changes
Второй cls файл я увидела, но нет строк для переключения стиля
Я вам писала, что формулы легкие, вы добавляли что-то сложнее?

2024-05-07 05:19 UTC, Deemeed commented
А как это "строк для переключения стиля"? В первой строке /documentclass меняем название cls файла и всё работает

2024-05-07 11:13 UTC, Olga1140 commented
Все работает без ошибок? Отлично, иногда нужно добавлять несколько строк. Напишите тогда второй раз documentclass и закомментируйте, так я быстрее поменяю шаблон

2024-05-07 11:21 UTC, Olga1140 commented
Вы читали 2 пункт в самых первых моих замечаниях? Вы его выполнили?

2024-05-07 15:58 UTC, Deemeed commented
Сейчас добавили строку \documentclass для быстрого переключения между стилями и сложную формулу (нумерованная (3) )

2024-05-07 19:13 UTC, Olga1140 requested changes
Шаблон volcanica-template компилируется с ошибками

2024-05-07 19:13 UTC, Olga1140 commented on sample-acmlarge.tex
> +    \int_{\mathbb{R}^n} \exp\left( -\frac{1}{2} x^T A x + b^T x \right) dx = \sqrt{\frac{(2\pi)^n}{\det A}} \exp\left( \frac{1}{2} b^T A^{-1} b \right),
Пределы интегрирования принято записывать не справа от интеграла, а сверху и снизу

2024-05-08 08:36 UTC, Deemeed commented
Предел теперь стоит правильно и второй файл компилируется без ошибок

2024-05-08 18:38 UTC, Olga1140 commented
У меня ошибки вылезают все равно, проверьте, возможно, вы удалили строки, думая, что они не нужны, а без них теперь шаблон нормально не работает
Я правильно понимаю, что вы не исправили прошлые ошибки, а просто поменяли шаблон?

2024-05-09 12:29 UTC, Deemeed commented
Поменяли, а разве желтые это тоже ошибки? Все говорят с ними отправляли и принимали лабы.

2024-05-09 12:40 UTC, Olga1140 commented
С желтыми принимаю, с красными нет, а на втором шаблоне вылезают красные

2024-05-09 12:40 UTC, Olga1140 commented
Попробуйте скачать архив и скомпилировать его

2024-05-09 13:01 UTC, Deemeed commented
А в каких строках красные? Я скачал и скомпилировал архив и у меня так же только желтые

2024-05-09 13:06 UTC, Olga1140 commented
Пришлите скрин

2024-05-09 13:27 UTC, Deemeed commented
![Снимок экрана 2024-05-09 172027](https://github.com/itsecd/academic-fundamentals/assets/161116227/08ce1c6f-ea4b-4d6e-9598-2d07f7454674)
![Снимок экрана 2024-05-09 172137](https://github.com/itsecd/academic-fundamentals/assets/161116227/3cab7511-229d-4461-8d2d-172de8b8f647)
![Снимок экрана 2024-05-09 172128](https://github.com/itsecd/academic-fundamentals/assets/161116227/b0576fa2-952c-4540-9dcb-c9bb4bdc339b)
![Снимок экрана 2024-05-09 172115](https://github.com/itsecd/academic-fundamentals/assets/161116227/fd4b9855-2a36-44c1-9137-ac0266370704)
![Снимок экрана 2024-05-09 172101](https://github.com/itsecd/academic-fundamentals/assets/161116227/14967b62-90a5-43f3-b045-5f54f3a06100)

2024-05-09 13:32 UTC, Olga1140 commented
Видите наверху красный прямоугольник с цифрой 2?

2024-05-09 13:32 UTC, Olga1140 commented
Значит, ошибки есть

2024-05-09 13:44 UTC, Olga1140 commented
В ошибке написано, что команда \proof уже определена, значит, это что-то связанное с теоремами. У вас есть пакет для теорем. Если его убрать, то все будет нормально

2024-05-09 15:24 UTC, Deemeed commented
Удалили пакет, теперь ошибок нет

2024-05-09 15:28 UTC, Olga1140 commented
Понятно, что теперь их нет, я вам сама сказала, в чем она заключалась, и что нужно удалить, чтобы она пропала

2024-05-09 16:05 UTC, Deemeed commented
Нужно что-то еще поправить?

2024-05-09 16:19 UTC, Olga1140 commented
Нет, вам же до 9 мая сказали внести все изменения, поэтому сегодня уже все

2024-05-09 16:48 UTC, Olga1140 commented
В том, что вы прислали до 9 мая были ошибки, поэтому нет

2024-05-16 04:18 UTC, closed without merging