6112 Lab2L Симонов Голосов
itsecd/academic-fundamentals pull request #133
Opened 2024-04-23 18:58 UTC by keshacheshek

Здравствуйте, в архиве находятся word документ, измененный под стиль книги (присутствует в архиве), документ TEX и 2 изображения к нему

2024-04-24 21:28 UTC, Olga1140 requested changes
Добрый вечер
1 Не выполнен 3 пункт
2 Если в тексте есть переменные и параметры, их надо выделять долларами, чтобы они от текста отличались

2024-04-24 21:28 UTC, Olga1140 commented on 6112 Lab2L Симонов Голосов .tex
> +\noindent where \  $a_{i,r+1}^{M_0}${}- matrix element;
Добавьте "где..." в строку с самой формулой

2024-04-24 21:28 UTC, Olga1140 commented on 6112 Lab2L Симонов Голосов .tex
> +\begin{matrix}a_{0,0}&a_{0,0}&
Как-то странно матрица у вас вводится

2024-04-25 11:01 UTC, IMPULSE-LAB-CRYPTO commented
Здравствуйте, вот исправленный тех документ в архиве (все переменные были записаны в $, матрица была записана в адекватном виде, cls документ добавлен)
[LaTeX.zip](https://github.com/itsecd/academic-fundamentals/files/15108543/LaTeX.zip)

2024-04-27 09:26 UTC, Olga1140 commented
Я не нашла в архиве tex файл

2024-04-27 11:35 UTC, IMPULSE-LAB-CRYPTO commented
Прошу прощения, должен был быть. Вот здесь есть
[LaTeX.zip](https://github.com/itsecd/academic-fundamentals/files/15138025/LaTeX.zip)

2024-04-29 06:40 UTC, Olga1140 commented on 6112 Lab2L Симонов Голосов .tex
> +\noindent where \  $a_{i,r+1}^{M_0}${}- matrix element;
Это вы не сделали. "где..." осталось на том же месте

2024-04-29 06:45 UTC, Olga1140 commented
Сделайте еще один стиль. Вам же в задании написали 2 сделать, да? Отдельный tex файл создавать не надо. Просто напишите в этом файле строки для переключения стиля, а строки для старого стиля закомментируйте

2024-05-01 19:18 UTC, IMPULSE-LAB-CRYPTO commented
Добрый вечер! Вот второй вариант документа, оформленного в другом стиле. Я сделал отдельным архивом файлов, думаю так будет правильнее, нежели чем комментировать.
[LaTeX_2.zip](https://github.com/itsecd/academic-fundamentals/files/15180441/LaTeX_2.zip)

2024-05-05 04:24 UTC, Olga1140 commented
Отдельный tex файл создавать не надо. Просто напишите в этом файле строки для переключения стиля, а строки для старого стиля закомментируйте
Смысл этого задания в том, чтобы вы немного поменяли код, а стиль всего документа сразу поменялся. Поэтому сделайте, пожалуйста, так, как я вас попросила, думаю, так будет правильнее

2024-05-06 19:57 UTC, IMPULSE-LAB-CRYPTO commented
Доброго времени суток! Вот я добавил стиль biometrika и закомментировал optica-article как вы и сказали. Все работает.
[hhh.zip](https://github.com/itsecd/academic-fundamentals/files/15225740/hhh.zip)
[После.pdf](https://github.com/itsecd/academic-fundamentals/files/15225712/default.pdf)
[До.pdf](https://github.com/itsecd/academic-fundamentals/files/15225711/default.pdf)

2024-05-07 11:10 UTC, Olga1140 requested changes
1 Насколько я помню, у вас была нормальная матрица, что вы с ней сделали?
2 Один комментарий мой вы игнорируете
3 Также я заметила, что у вас нет нумерованной формулы

2024-05-07 15:29 UTC, IMPULSE-LAB-CRYPTO commented
1) Точки в записи прежнего вида добавил. Да, матрица была записана с помощью \matrix, однако для подключения другого стиля она отображалась некорректно, поэтому я исправил её с помощью \tabular. 
2) Я стараюсь выполнять все ваши указания, про что именно вы говорите? Если про стили, то я сделал всё, как вы говорили. Изменил свой первый документ тех ([LaTeX.zip](https://github.com/itsecd/academic-fundamentals/files/15138025/LaTeX.zip), лишь добавив в него стиль biometrika и закомментировав \userpackage{optica-article} который использовался в первый раз
3) Я показывал Виктору Андреевичу этот вариант, объяснив ему, что у меня не было в изначальном документе нумерованной формулы, поэтому он сказал не делать её, ввиду того что в моем шаблоне не были только формулы без нумерования

Измененный архив(матрица подправлена, старый стиль закомментирован, через \userpackage подключил новый: два cls документа добавлены): 
[Volcanica LaTeX Template (1) (1).zip](https://github.com/itsecd/academic-fundamentals/files/15237673/Volcanica.LaTeX.Template.1.1.zip)

Также хотел бы вам напомнить от имени старосты, моя одногруппница Черникова Полина (совместно с Кривоносовой Екатериной) не может получить от вас ответ на ее пул реквест по Латеху с 25 апреля. Это какая-то ошибка с их стороны? Обратите пожалуйста на это внимание, спасибо!

2024-05-07 15:46 UTC, Olga1140 commented
Спасибо, что сообщили про Черникову, видимо, когда все в последний день все начали скидывать, как-то пропустила их

2024-05-07 15:48 UTC, Olga1140 commented
Передайте им, что сегодня начну проверку с них, как только смогу за это сесть

2024-05-07 18:57 UTC, Olga1140 requested changes
1 Оба стиля компилируются с ошибкой, возможно, вы какие-то строки забыли написать. Для того, чтобы шаблон нормально заработал, часто нужно не только поменять \documentclass, но и добавить какие-то строки. Некоторые стили требуют авторов, название и т.д.
2 По поводу замечания. которое вы пропускаете. Я вам 2 раза писала про "где..."
3 Добавьте, пожалуйста, все таки нумерованную формулу, потом уберете, когда я зачту этот момент

2024-05-07 20:30 UTC, IMPULSE-LAB-CRYPTO commented
Добрый вечер! У меня наконец получилось переключить разные стили (оказывается преамбула, про которую вы написали тоже важна. После исправления строчки теперь не считает за ошибку).
1) Теперь стили компилируются без ошибок
2) слово "where" я вставил в саму строчку с формулой (до этого думал, что ее нужно просто засунуть в пространство для обозначения формулы, тобишь просто в знаки $)
3)Сделал нумерованную формулу (Плюсом дополнил ее ссылкой, если нужно)

Измененный файл:
[Volcanica LaTeX Template (1) (2).zip](https://github.com/itsecd/academic-fundamentals/files/15240600/Volcanica.LaTeX.Template.1.2.zip)

2024-05-08 05:43 UTC, Olga1140 commented
"где" нужно было вставить вместе с пояснением, я поэтому там многоточие писала, ну это ладно, теперь у вас это слово написано курсивым, так? А остальной текст так не пишется, надо это исправить

В остальном все хорошо, исправьте последнее замечание, тогда я смогу вас отпустить. Можете прислать исправление не архивом, а просто скрин сделать, на котором видно исправленное место и в коде, и в pdf

2024-05-08 07:36 UTC, IMPULSE-LAB-CRYPTO commented
Вот таким образом нужно это сделать? 
![image](https://github.com/itsecd/academic-fundamentals/assets/57728215/9d9fcaee-c122-4a40-9f71-29437640317d)

2024-05-08 18:24 UTC, Olga1140 commented
Хорошо, работа зачтена

2024-05-08 18:24 UTC, Olga1140 approved these changes

2024-05-16 04:18 UTC, closed without merging