6112 Lab2L Бынеев Черепков
itsecd/academic-fundamentals pull request #134
Opened 2024-04-24 08:16 UTC by Dimas750

2024-04-27 03:39 UTC, Olga1140 requested changes
1 Не выполнен 3 пункт задания
2 Если в тексте есть переменные и параметры, их надо выделять долларами
3 Перенесите "где..." в строку, где находится сама формула
4 (1) и (3) формулы достаточно простые

2024-04-27 03:39 UTC, Olga1140 commented on main.tex
> +t=(\frac{1}{2*R*M})-(\frac{R}{M}-1)*B*H \label{5}
Маленькие скобки

2024-05-04 19:25 UTC, Dimas750 commented
Здравствуйте, исправил замечания и выполнил 3 пункт, пдфки приложил

2024-05-06 15:02 UTC, Olga1140 commented
Я посмотрела. Как я поняла, я увидела пример с сайта Overleaf (я не знаю, зачем он там, наверное, для того, чтобы я его проверять начала, думая, что это ваша работа), еще увидела код, как я понимаю ваш, в котором вылезают ошибки

2024-05-06 16:33 UTC, Dimas750 commented
Здравствуйте, в двух пдф файлах в которых я применял разные стили содержится мой текст, а в самом зип архиве мой код, который я перенёс на шаблон, возможно в том зип архиве вы увидели не удалённые файлы с шаблона, сейчас я всё подправил и загрузил

2024-05-07 06:37 UTC, Olga1140 requested changes
1 У вас вылезают ошибки, когда вы стиль меняете на rho?
2 Второй пункт из моего первого замечания
3 У вас сумма записалась так, как вы и хотели?

2024-05-07 17:06 UTC, Dimas750 commented
Заменил новый стиль и теперь код вроде бы без ошибок, подправил запись суммы во второй формуле, все переменные и параметры взял в доллары

2024-05-07 19:25 UTC, Olga1140 commented
Посмотрите еще разок на формулу (3), точно ли она так должна выглядеть?

Если я правильно помню причину вашей прошлой ошибки, она заключалась вот в чем: этот шаблон очень хотел, чтобы вы ему сказали название работы, авторов и т.д. То, что он пишет в колонтитулах

2024-05-07 19:50 UTC, Dimas750 commented
А мне сейчас нужно написать авторов или только исправить формулу?

2024-05-07 20:31 UTC, Dimas750 commented
В общем я переделал 3 формулу, она и правда была слегка не такая. На счёт заголовков и колонтитулов вышло довольно странно у меня. Как вы увидите в коде в комментариях некоторые части кода нужно будет убирать под знак %, чтобы корректно работал тот или иной стиль. Как я понял это из-за того что у стилей разные стандарты колонтитулов. И на счёт авторов возможно я мог понять неправильно и написал помимо реальных авторов статьи ещё и нас с напарником. Так же в стиле informs4.cls не смог убрать надпись красным цветом после названия и авторов. В остальном вроде проблем быть не должно. Извиняюсь что придётся комментировать некоторые части коды для нормальной работы стилей, наверное можно было адаптировать, но я не до конца понял как

2024-05-08 05:35 UTC, Olga1140 commented
1 Теперь формула приняла привычный для меня вид, спасибо.
2 По поводу красного цвета: Вы можете открыть cls файл 2035 строку, он там задается
3 В авторах да, надо писать себя, а остальных можно удалять.
4 А по поводу комментариев, то тут деваться некуда, максимум, что можно сделать, собрать в кучу все для одного шаблона, отдельно для другого, чтобы удобнее было переключать. Как по мне, это лучше, чем заново все создавать, если захотелось к другому виду документа перейти.

5 У вас эти стили разве до этого выдавали ошибки? Вроде, нет. Это все в обязательном порядке хотел видеть у себя стиль rho, нет?

Переделывать уже  ничего не надо, просто ответьте на 5 вопрос

2024-05-08 05:52 UTC, Dimas750 commented
До этого выдавал стиль rho ошибки, наверное он этого и хотел, но я решил на всякий случай переделать на другой стиль и он работает идеально без ошибок

2024-05-08 05:54 UTC, Olga1140 commented
То есть, в этих стилях Вы могли ничего такого и не делать, так?

2024-05-08 05:54 UTC, Olga1140 approved these changes

2024-05-08 05:55 UTC, Dimas750 commented
Ну изначально работали эти стили без колонтитулов и авторов, так что наверное мог

2024-05-08 05:55 UTC, Dimas750 commented
Ну я уж сделал, чтобы наверняка

2024-05-08 05:56 UTC, Olga1140 commented
Понятно, я зачла работу

2024-05-08 05:59 UTC, Dimas750 commented
Хорошо, спасибо

2024-05-16 04:17 UTC, closed without merging