6114 Lab2L Алмаев Голенков
itsecd/academic-fundamentals pull request #135
Opened 2024-04-24 13:44 UTC by VictorGolenkov

2024-04-27 03:49 UTC, Olga1140 requested changes
1 Если в тексте есть параметры и переменные, их надо выделять долларами

Остальное засчитано, молодцы)

2024-04-27 03:49 UTC, Olga1140 commented on main(1).tex
> +			\min\nolimits_{\omega\in{R^d}}\sum _{i=1}^n loss(\omega^T x_i,y_i)
Сделайте ограничение не справа от min, а снизу

2024-04-28 07:56 UTC, VictorGolenkov commented
Исправил

2024-04-29 07:52 UTC, Olga1140 approved these changes

2024-05-16 04:17 UTC, closed without merging