6111 Lab2L Delibaltov Kalinovskaya
itsecd/academic-fundamentals pull request #136
Opened 2024-04-24 15:16 UTC by IvanDelibaltov

2024-04-25 05:25 UTC, IvanDelibaltov commented
[JMLR Template 2.zip](https://github.com/itsecd/academic-fundamentals/files/15104587/JMLR.Template.2.zip)

2024-04-27 04:04 UTC, Olga1140 requested changes
У вас 2 архиве. Какой я должна скачать для проверки?

2024-05-03 10:05 UTC, IvanDelibaltov commented
Здравствуйте. Template 2

2024-05-05 10:36 UTC, Olga1140 requested changes
1 Почему у вас нет отдельного tex файла?
2 Вам сказали выбрать 2 шаблона
3 Список должен быть автоматическим
4 Сделайте так, чтобы числитель и знаменатель не уменьшались
5 Первая формула достаточно простая

2024-05-05 17:31 UTC, IvanDelibaltov commented
[latex.zip](https://github.com/itsecd/academic-fundamentals/files/15213871/latex.zip)
[oni.pdf](https://github.com/itsecd/academic-fundamentals/files/15213872/oni.pdf)
Здраствуйте, с исправлениями)

2024-05-06 17:23 UTC, Olga1140 commented
Проверьте, пожалуйста, правильный ли вы архив прислали. Также проверьте, все ли замечания были исправлены

2024-05-07 17:39 UTC, IvanDelibaltov commented
Можете пожалуйста написать что именно нужно исправить.

2024-05-07 17:43 UTC, Olga1140 commented
Добрый вечер, я сейчас точно  не скажу, так как не помню, но так я пишу, когда архив либо пустой, либо код не работает, либо что-то странное с кодом

2024-05-07 17:58 UTC, IvanDelibaltov commented
[ezyzip.zip](https://github.com/itsecd/academic-fundamentals/files/15239146/ezyzip.zip)
[oni.pdf](https://github.com/itsecd/academic-fundamentals/files/15239147/oni.pdf)
Здравствуйте, переотправляю файл (через другой сайт запаковала).

2024-05-07 19:40 UTC, Olga1140 commented
Как я уже писала, в задании написано, чтобы вы выбрали 2 шаблона. Добавьте строки для подключения второго в свой tex файл, Строки для первого шаблона закомментируйте

Остальное нормально, доделывайте и присылайте

2024-05-08 17:25 UTC, IvanDelibaltov commented
[ezyzip.zip](https://github.com/itsecd/academic-fundamentals/files/15252623/ezyzip.zip)

2024-05-09 12:09 UTC, Olga1140 commented
Второй шаблон компилируется с ошибками, возможно, шаблон хочет узнать название, авторов. Это все должно быть в примере, который идет вместе с cls файлом. Вы их, наверное, удалили.

Учитывая это замечание, работу я вам зачесть не могу

2024-05-16 04:17 UTC, closed without merging