6111 Lab2L Zhestkov Magomedagaev
itsecd/academic-fundamentals pull request #138
Opened 2024-04-24 19:19 UTC by mappy12

2024-04-27 04:32 UTC, Olga1140 requested changes
1 Нет отдельного тех файла
2 3 пункт не выполнен
3 Скобки не должны быть меньше размера выражения в скобках
4 Если в тексте есть переменные и параметры, их нужно выделять долларами
5 Логарифм записывается не так, он должен быть не курсивым

2024-04-27 11:11 UTC, mappy12 commented
1. TEX файл - файл, который непосредственно содержит код. Он находится в zip-архиве, какой еще TEX файл я должен прикрепить отдельно?
2. 3 пункт - задание по LATEX. Что именно я не выполнил? Подозреваю, что не заменил .cls файл на другой.
3. Исправил.
4. Вроде бы все переменные, которые есть в тексте я выделял долларами(преимущественно они находились после формул). Если вы имеете ввиду: "PSNR", "MSE", "MOS" и тд., то это - аббревиатуры (но на всякий случай их тоже выделил долларами).
5. Исправил.


Подскажите пожалуйста, как исправленный вариант вам отправлять? Я прикреплю zip-файл. Напишите пожалуйста, если нужно делать как-то по-другому.
[Zhestkov_Magomedagaev_Latex(fixed).zip](https://github.com/itsecd/academic-fundamentals/files/15137979/Zhestkov_Magomedagaev_Latex.fixed.zip)

2024-04-28 12:00 UTC, Olga1140 commented
Что вам сказали прикрепить в github для проверки?

2024-04-28 15:49 UTC, mappy12 commented
[Zhestkov_Magomedagaev_Latex_2.0.zip](https://github.com/itsecd/academic-fundamentals/files/15142645/Zhestkov_Magomedagaev_Latex_2.0.zip)
[Zhestkov_Magomedagaev.txt](https://github.com/itsecd/academic-fundamentals/files/15142664/Zhestkov_Magomedagaev.txt)

2024-04-29 11:15 UTC, Olga1140 commented
В списке файлов (где находятся папки с заданиями по лабам, лекциям, ваши файлы по лабам) должны быть tex файл и zip  архив для 2 лабораторной

2024-04-29 12:03 UTC, mappy12 commented
Сделал. Название файлов: Zhestkov_Magomedagaev_Latex_2.0.zip и Zhestkov_Magomedagaev.txt (TEX)

2024-05-01 11:09 UTC, Olga1140 requested changes
1 Ненужные файлы надо удалять, чтобы мне не пришлось гадать, что именно мне надо скачивать
2 3 пункт задания по latex так и не выполнен
3 Аббревиатуры в долларах записывать не надо, у вас параметры без них были

2024-05-01 11:09 UTC, Olga1140 commented on Zhestkov_Magomedagaev.txt
> +    UIQI(x,y)=I(x,y)*c(x,y)*s(x,y)=\frac{4\mu_x\mu_y\mu_xy}{(\mu_x^2+\mu_y^2)*(\sigma_x^2+\sigma_y^2)}.
Скобки не должны быть меньше размера выражения в скобках

2024-05-01 11:09 UTC, Olga1140 commented on Zhestkov_Magomedagaev.txt
> +The clarity of image is expected to decrease when a motion or blur distortion is applied. And, the clarity of image is expected to increase when a sharpening is applied. Accordingly, the $SIMM$ and $
Для sigma есть команда, чтобы вывелась буква, а не слово

2024-05-03 15:31 UTC, mappy12 commented
1. Удалять не получается. Поэтому я пишу название файлов, которые нужно скачивать.
2. О каком 3 пункте идет речь? Latex-часть в принципе не рабита на части.

2024-05-03 15:37 UTC, mappy12 commented on Zhestkov_Magomedagaev.txt
> +The clarity of image is expected to decrease when a motion or blur distortion is applied. And, the clarity of image is expected to increase when a sharpening is applied. Accordingly, the $SIMM$ and $
Исправил.

2024-05-05 10:18 UTC, Olga1140 commented
3 В 3 пункте вам говорится в основном о том, что вы должны применять cls файлы, вот про это я вам писала

2024-05-05 12:47 UTC, Olga1140 requested changes
Как я уже писала раньше, нет шаблонов
В какой-то формуле напишите "где...." в строке с самой формулой

2024-05-07 09:07 UTC, Olga1140 requested changes
1 Один шаблон увидела, добавьте строки для подключения второго шаблона

2024-05-07 13:35 UTC, Olga1140 commented
Нужно написать строки, необходимые для второго шаблона, Строки для первого шаблона закомментировать

2024-05-07 15:38 UTC, mappy12 commented
готово.

2024-05-07 19:06 UTC, Olga1140 requested changes
При компиляции с шаблоном joas вылезают ошибки, посмотрите, может, вы что-то забыли взять из того шаблона

2024-05-08 04:32 UTC, mappy12 commented
У меня все компилировалось, но да, были ошибки по типу "undefined control sequence?". Я залез еще раз в тот шаблон, и не нашел того, что еще можно добавить для работы в моем проекте. Поэтому принял решение поменять joas на lni. Вроде все работает.
[Zhestkov_Magomedagaev_Latex_6.0.zip](https://github.com/itsecd/academic-fundamentals/files/15243847/Zhestkov_Magomedagaev_Latex_6.0.zip)
[Zhestkov_Magomedagaev_6.0.txt](https://github.com/itsecd/academic-fundamentals/files/15243848/Zhestkov_Magomedagaev_6.0.txt)

2024-05-08 17:46 UTC, Olga1140 commented
Я посмотрела ваш шаблон, у вас раньше была папка со всеми файлами, так как вы ее убрали, вы должны были поменять все строки, в которых используется эта папка. Например, у вашего шаблона был логотип, но вы даже картинку его не вставили.
Кроме этого шаблоны часто хотят увидеть название и авторов

2024-05-08 17:47 UTC, Olga1140 approved these changes

2024-05-16 04:17 UTC, closed without merging