6112 Lab2L Krivonosova Chernikova
itsecd/academic-fundamentals pull request #139
Opened 2024-04-24 19:22 UTC by https-katice

2024-05-07 18:34 UTC, Olga1140 requested changes
1 В коде ошибка
2 Нет оглавления
3 У вас первые две формулы похожи, а третья очень легкая, добавьте еще что-то посложнее, что не будет похоже на первые две
4 Добавьте строки для подключения второго шаблона, строки для первого закомментируйте

Так как я долго вам не отвечала, я поставлю сдачу не в тот день, когда вы мне сдадите лабу, а раньше, чтобы эта ситуация не повлияла на ваш результат

2024-05-07 18:34 UTC, Olga1140 commented on 6112 Krivonosova Chernikova.tex
> +\eta_{ij}^{mn} = \sigma{(b_{ij}+\sum\nolimits_{\delta}\sum\nolimits_{p=0}^{P_{i}-1}\sum\nolimits_{q=0}^{Q_{i}-1}}\omega_{ij}^{pq})\,
Ограничения принято указывать не справа от суммы, а сверху и снизу
Напишите "где..." в одной строке с формулой
Скобки маленькие

2024-05-08 19:01 UTC, Olga1140 commented
При переключении на второй стиль вылезают ошибки
Пришлите исправленный файл архивом

2024-05-09 13:36 UTC, https-katice commented
[ОНИ2.2.zip](https://github.com/itsecd/academic-fundamentals/files/15262928/2.2.zip)

2024-05-09 18:52 UTC, https-katice commented
Код выдает ошибку по причине того, что в стиле не предусмотрено содержание, это прописывает сам латех, все остальное было пофикшено и ошибки больше не выдает

2024-05-15 18:26 UTC, Olga1140 commented
Нет, посмотрите на пример с этим шаблоном, попробуйте понять, в чем разница. Если не поймете, я скажу, что не так, но оценка будет хуже

2024-05-16 04:17 UTC, closed without merging