6113 Lab2L Козлов Завадский
itsecd/academic-fundamentals pull request #147
Opened 2024-04-25 06:05 UTC by nikzavadskiy

[6113 Lab2L Козлов Завадский.zip](https://github.com/itsecd/academic-fundamentals/files/15104979/6113.Lab2L.zip)

2024-04-27 06:11 UTC, Olga1140 requested changes
Не прикреплен отдельно tex файл

2024-04-29 11:17 UTC, Olga1140 requested changes
1 Проверьте, все ли задания выполнены
2 Проверьте, нет ли ошибок в коде

2024-05-09 15:13 UTC, nikzavadskiy commented on 6113 lab2L.tex
> +        0 & \setminus & 0 \\
задания должны быть все выполнены, мы делали их в соответствии с написанным.

2024-05-09 15:18 UTC, Olga1140 commented
Вы не выполнили 3 пункт про шаблоны, без них работа не принимается, я вам писала, чтобы вы проверили, все ли задания выполнены. В любом случае, сегодня я уже не принимаю работы, все изменения вам сказали прислать до сегодняшнего дня

2024-05-09 15:46 UTC, nikzavadskiy commented
Ой, извиняюсь, по невнимательности был загружен не тот zip файл. Я поэтому был удивлен, что у нас есть какое-то не выполненное задание, хотя мы все делали строго по инструкции.
 Можно ли это считать за внесение изменений, никаких правок же внесено не было? Еще раз извините за потраченное время.
[6113 Lab2L Козлов Завадский.zip](https://github.com/itsecd/academic-fundamentals/files/15264413/6113.Lab2L.zip)

2024-05-16 04:17 UTC, closed without merging