6112 Lab2L Наумов Ильин
itsecd/academic-fundamentals pull request #152
Opened 2024-04-25 09:54 UTC by naumoffIE

[lab2-3.pdf](https://github.com/itsecd/academic-fundamentals/files/15107798/lab2-3.pdf)
[lab2-3.zip](https://github.com/itsecd/academic-fundamentals/files/15107799/lab2-3.zip)

2024-04-27 09:16 UTC, Olga1140 requested changes
1 Если в тексте есть параметры и переменные, их надо выделять долларами
2 Напишите "где..." в одну строку с самой формулой
3 Вам в задании написали, что формулы должны быть не очень простыми
4 Добавьте второй стиль. В этом же tex файле напишите строки для переключения стиля, строки для первого нужно закоментировать

2024-05-09 12:15 UTC, Olga1140 commented
Изменения увидела только по 4 замечанию (шаблон, кстати, прикольный). По остальным изменений не увидела, поэтому работу зачесть не могу

2024-05-09 13:19 UTC, naumoffIE commented
Здравстуйте, отправил немного не то.
[Coding Book Template (1).zip](https://github.com/itsecd/academic-fundamentals/files/15262771/Coding.Book.Template.1.zip)
[Coding_Book_Template (1).pdf](https://github.com/itsecd/academic-fundamentals/files/15262782/Coding_Book_Template.1.pdf)
По первому пункту так и не нашел, что я пропустил

2024-05-09 13:34 UTC, Olga1140 commented
Теперь, значит, будете проверять, что вы отправляете преподавателю

2024-05-16 04:17 UTC, closed without merging