6114 Lab2L Отюбрин
itsecd/academic-fundamentals pull request #156
Opened 2024-04-25 10:27 UTC by OtyubrinRoma

2024-04-27 09:22 UTC, Olga1140 requested changes
В дискорде есть сообщение, в котором написано, что и как прикреплять для второй лабораторной

2024-04-27 19:52 UTC, OtyubrinRoma commented
Переотправил.

2024-04-29 07:01 UTC, Olga1140 commented
Я увидела 2 архива. Мне нужен только один архив. Если у вас архивы для разных стилей, соедините их в один. Причем Tex файл должен быть только один. В нем должны быть строки для переключения шаблона. Для одного из стилей строки просто закомментируйте

2024-04-29 11:44 UTC, Olga1140 requested changes
1 Я Вас попросила для одного из стилей строки написать, но закомментировать
2 Пределы интегрирования принято записывать сверху и снизу интеграла, а не справа
3 У Вас однотипные формулы, добавьте что-то еще

2024-04-29 11:44 UTC, Olga1140 commented on article.tex
> +We used $\int_{0}^{\infty} z^{a-1} e^{-bz} dy = \frac{\Gamma(a)}{b^a}$; for integer $n$ we have $\Gamma(n) = (n - 1)!$.
Сделайте так, чтобы числитель и знаменатель не уменьшались

2024-05-01 14:38 UTC, OtyubrinRoma commented
Внёс изменения

2024-05-04 18:46 UTC, Olga1140 requested changes
Как только исправите последние замечания, зачту Вам работу

2024-05-04 18:46 UTC, Olga1140 commented on article.tex
> +\sim r -1 dr$. This basically says that log r is distributed uniformly: the probability of $r \in [a,b]$ is proportional to $log(\frac{b}{a})$. For example, $r \in [1,10]$ and $r \in [10,100]$ have t
Логарифм написан курсивым, так не должно быть. Скобки слишком маленькие

2024-05-04 18:46 UTC, Olga1140 commented on article.tex
> +where $P(r)$ – our prior information about the rate $r$.
Добавьте "где... " в строку с самой формулой

2024-05-06 12:01 UTC, OtyubrinRoma commented
Внёс изменения

2024-05-06 17:49 UTC, Olga1140 commented on article.tex
> +where $P(r)$ – our prior information about the rate $r$.
Хорошо, но Вы могли написать проще:
\text{where $P(r)$ – our prior information about the rate }

2024-05-06 17:52 UTC, Olga1140 commented on article.tex
> +where $P(r)$ – our prior information about the rate $r$.
github доллары убрал в прошлом сообщении. То есть, Вы могли P(r) просто взять в долларах внутри команды \text

2024-05-06 17:52 UTC, Olga1140 approved these changes

2024-05-06 20:45 UTC, closed without merging