6112 Lab2L Рыжков
itsecd/academic-fundamentals pull request #162
Opened 2024-04-25 14:10 UTC by Ryzkov

2024-04-27 09:40 UTC, Olga1140 requested changes
Прочитайте еще раз, что написано про формулы в задании

2024-04-27 09:40 UTC, Olga1140 commented on main.tex
> +where $I_U(u)$ is the unknown variable;\\
Напишите "где..." в строке с самой формулой

2024-05-02 16:23 UTC, Ryzkov commented
Добавил нумерацию формул и написал "где...." в стоке с формулой

2024-05-05 07:29 UTC, Olga1140 commented
Куда Вы добавили изменения? Я скачиваю архив, там я не увидела изменений

2024-05-05 08:36 UTC, Ryzkov commented
Добавил архив с измененным main.
[lab2.3 исп.zip](https://github.com/itsecd/academic-fundamentals/files/15212232/lab2.3.zip)

2024-05-06 16:36 UTC, Olga1140 commented on main.tex
> +where $I_U(u)$ is the unknown variable;\\
"где" не должно быть курсивым. Нет пояснения после "где"

2024-05-06 16:40 UTC, Olga1140 commented
Когда я писала, что надо посмотреть, что написано про формулы, я имела ввиду не только нумерацию. Как Вы думаете, Ваши формулы можно засчитать за 3 не слишком легкие? 2 одинаковые, только буквы поменялись, третья вообще маленькая. Добавьте что-то еще (сложнее). В одну из первых можете добавить ограничения для суммы.

2024-05-08 14:09 UTC, Ryzkov commented
Исправил "где......", заменил третью формулу на более сложную, во второй формуле добавил ограничения на суммы.
[lab2.3исп2.zip](https://github.com/itsecd/academic-fundamentals/files/15250023/lab2.3.2.zip)

2024-05-09 09:20 UTC, Olga1140 commented
Хорошо, а можете сказать, где найти архив со вторым шаблоном?

2024-05-09 11:19 UTC, Ryzkov commented
[lab2.3cls2.zip](https://github.com/itsecd/academic-fundamentals/files/15261535/lab2.3cls2.zip)
Второй шаблон

2024-05-09 11:23 UTC, Olga1140 commented
То есть, изначально его не было? В задании написано, что 2 шаблона выбрать надо

2024-05-09 11:29 UTC, Olga1140 commented
Я посмотрела. Вы видели, как скомпилировался файл? Ошибки вылезали какие-то? В самом документе все нормально было?

Дедлайн у вас 9 мая, изменения разрешили вносить до этого числа

2024-05-09 11:37 UTC, Ryzkov commented
Два предупреждения(желтого цвета), в документе все нормально.

2024-05-09 11:45 UTC, Olga1140 commented
Пришлите скрин компиляции именно этого архива

2024-05-09 11:50 UTC, Ryzkov commented
![Снимок экрана (329)](https://github.com/itsecd/academic-fundamentals/assets/166698004/b02be195-236f-484a-9def-4f504081718d)
![Снимок экрана (328)](https://github.com/itsecd/academic-fundamentals/assets/166698004/76c7b246-6506-4c62-aa34-b450ff843f93)
Появилась ошибка из за того, что я не добавил в архив папку figs с png логотипа

2024-05-09 11:52 UTC, Ryzkov commented
![Снимок экрана (330)](https://github.com/itsecd/academic-fundamentals/assets/166698004/9abe2429-1a7a-48d8-936a-cd651241a42e)
![Снимок экрана (331)](https://github.com/itsecd/academic-fundamentals/assets/166698004/0044e345-5dda-4cfc-ad58-6ea1a7af3825)
С этой папкой выглядит вот так

2024-05-09 11:52 UTC, Olga1140 commented
Советую проверять файлы, которые вы отправляете преподавателям

2024-05-09 14:16 UTC, Olga1140 commented
Я увидела, что Вы прислали новый архив, но, как я уже напоминала, изменения нужно было вносить до 9 мая. Сегодня уже не "до 9 мая"

2024-05-16 04:17 UTC, closed without merging