6111 Lab2L Дмитриев Астафьев
itsecd/academic-fundamentals pull request #163
Opened 2024-04-26 12:48 UTC by dmitrievsn

2024-04-27 09:44 UTC, Olga1140 requested changes
Вам писали, в каком виде надо прикреплять файлы на проверку

2024-04-28 08:40 UTC, dmitrievsn commented
([lab_2.3.zip](https://github.com/itsecd/academic-fundamentals/files/15141389/lab_2.3.zip))
Не получается приложить файл main (1).tex отдельно

2024-04-29 11:10 UTC, Olga1140 requested changes
Где-то есть ошибка, код не работает

2024-04-30 10:46 UTC, dmitrievsn commented
[main.1.zip](https://github.com/itsecd/academic-fundamentals/files/15162069/main.1.zip)
[lab_2.3.zip](https://github.com/itsecd/academic-fundamentals/files/15162081/lab_2.3.zip)
Здравствуйте, попробуйте снова, пожалуйста, мы проверили на другом компьютере, вставив содержимое zip-файла в LaTeX'е, всё работает

2024-05-03 05:16 UTC, Olga1140 commented
То есть у вас ошибки не вылезают?

2024-05-03 07:59 UTC, dmitrievsn commented
![image](https://github.com/itsecd/academic-fundamentals/assets/163391506/81b3a751-f783-40c9-ae78-562c472c7c00)
[main (2).zip](https://github.com/itsecd/academic-fundamentals/files/15197417/main.2.zip)
[lab_2.3 (3).zip](https://github.com/itsecd/academic-fundamentals/files/15197415/lab_2.3.3.zip)
У нас все работает, мы немного переделали, пожалуйста попробуйте снова

2024-05-05 07:55 UTC, Olga1140 requested changes
Overleaf может компилировать даже тот код, в котором есть ошибки, но он показывает их. Поэтому я и спросила, вылезает ли у вас ошибка. Если вы будете писать статью, и отправите код с ошибками, могут быть проблемы. Попробуйте скачать тот архив, который вы мне сейчас прислали, у вас вылезает ошибка?

2024-05-05 07:55 UTC, Olga1140 commented on main (1).tex
> +        $$C=[{c_i}_j]+\lim_{n \to -\infty}(1+\frac{1}{i})^n\label{form}$$
Вам нужно заменить tex файл, так как здесь у вас есть ошибка, которую вы исправляли.

Скобки слишком маленькие

2024-05-05 07:55 UTC, Olga1140 commented on main (1).tex
> +    $A = \sum_{i=1}^n(z+v)\frac{a^i }{bc^j} + \lim_{n \to -\infty}(1+\frac{1}{i})^n$
Ограничения принято указывать не справа, а снизу и сверху
Скобки
Сделайте так, чтобы числитель и знаменатель не уменьшались

В третьей формуле аналогично

2024-05-06 11:24 UTC, dmitrievsn commented
исправил 
[main (3).zip](https://github.com/itsecd/academic-fundamentals/files/15219901/main.3.zip)

2024-05-06 17:43 UTC, Olga1140 commented
Заменить tex файл вам нужно в самом github. Исправления нужно присылать архивом со всеми необходимыми для компиляции файлами

2024-05-06 18:48 UTC, dmitrievsn commented
[1 (1).zip](https://github.com/itsecd/academic-fundamentals/files/15225147/1.1.zip)
вот исправления, tex файл заменил

2024-05-07 10:10 UTC, Olga1140 requested changes
1 Попробуйте скомпилировать то, что находится в архиве. будут ли вылезать ошибки? Все ли будет нормально?
2 В этом tex файле напишите строки для подключения второго шаблона (в задании сказано, что их 2 должно быть)

2024-05-07 12:24 UTC, dmitrievsn commented
но ошибки в самом коде не отмечаются

2024-05-07 12:28 UTC, Olga1140 commented
у меня другие ошибки вылезли

2024-05-07 12:37 UTC, dmitrievsn commented
и что делать?

2024-05-07 13:33 UTC, Olga1140 commented
Ошибку искать, ее очень легко заметить

2024-05-07 13:43 UTC, dmitrievsn commented
Нам нужно вот эту ошибку?output.bcf is malformed, last biblatex run probably failed. Deleted output.bbl
Если нет, то можете, пожалуйста, подсказать с чем именно связана эта ошибка?

2024-05-07 15:24 UTC, dmitrievsn commented
это код единственной ошибки,которую я нашел,у нас больше нет ошибок

2024-05-07 15:24 UTC, dmitrievsn commented
![image](https://github.com/itsecd/academic-fundamentals/assets/163391506/a1a644f5-0be1-49b7-b827-3c32d5434165)

2024-05-07 18:48 UTC, Olga1140 commented
Что мне делать с этой информацией?) Вы поняли, в чем ошибка была в том архиве, который последний мне был отправлен?

2024-05-07 21:40 UTC, dmitrievsn commented
Нет,не поняли

2024-05-08 05:45 UTC, Olga1140 commented
Скомпилируйте его и просмотрите, все ли скомпилировалось так, как вы хотели. Ту ошибку видно очень хорошо

2024-05-08 14:29 UTC, dmitrievsn commented
Добрый вечер, мы внесли правки
[main.zip](https://github.com/itsecd/academic-fundamentals/files/15250272/main.zip)
[acmart.zip](https://github.com/itsecd/academic-fundamentals/files/15250273/acmart.zip)

2024-05-09 09:28 UTC, Olga1140 commented
Отлично, ошибку вы все таки нашли, это радует, но второе замечание вы не исправили
Также запомните, что параметры и переменные записываются в долларах, чтобы было отличие от основного текста

2024-05-09 10:46 UTC, dmitrievsn commented
> Отлично, ошибку вы все таки нашли, это радует, но второе замечание вы не исправили Также запомните, что параметры и переменные записываются в долларах, чтобы было отличие от основного текста

Добрый день, параметры и переменные записал в долларах, запомнил на будущее
второе замечание исправил, второй cls-файл подключил, PDF-для второго cls сформировал

[main.zip](https://github.com/itsecd/academic-fundamentals/files/15261213/main.zip)
[main(acmart & volcanica-template).zip](https://github.com/itsecd/academic-fundamentals/files/15261215/main.acmart.volcanica-template.zip)

2024-05-09 10:53 UTC, Olga1140 commented
Вам до какого дня разрешили изменения вносить?

2024-05-09 10:56 UTC, Olga1140 commented
Я посмотрела, но я увидела ошибки, возможно, шаблон хочет увидеть название, или авторов, или еще что-то. Параметры я увидела, молодцы

2024-05-09 16:00 UTC, dmitrievsn commented
> Я посмотрела, но я увидела ошибки, возможно, шаблон хочет увидеть название, или авторов, или еще что-то. Параметры я увидела, молодцы
[main.zip](https://github.com/itsecd/academic-fundamentals/files/15264583/main.zip)
[main(acmart & spieman).zip](https://github.com/itsecd/academic-fundamentals/files/15264584/main.acmart.spieman.zip)
исправил
main.tex в PR изменить не могу, тк заморозили

2024-05-09 16:17 UTC, Olga1140 commented
Вам до какого дня разрешили изменения вносить? До 9 мая, сегодня уже не "до 9 мая"

2024-05-09 16:22 UTC, dmitrievsn commented
Ясно

2024-05-16 04:17 UTC, closed without merging