6112 lab2L Ладыгин Сергиенко
itsecd/academic-fundamentals pull request #164
Opened 2024-04-27 10:38 UTC by only-hell

2024-04-28 11:57 UTC, Olga1140 requested changes
В дискорде вам написали, какие файлы нужно прикреплять в github (у вас нет отдельного tex файла)

2024-04-29 18:30 UTC, only-hell commented
Отдельно прикрепить tex файл или же оставить его в zip?

2024-05-01 15:44 UTC, only-hell commented
![image](https://github.com/itsecd/academic-fundamentals/assets/91896993/7479a4f7-62a0-4141-84c4-5fbdafc0da0c)
![image2](https://github.com/itsecd/academic-fundamentals/assets/91896993/94139f53-f950-4513-b3c1-e34547e96f05)
[Lab2_3 Ладыгин Сергиенко.pdf](https://github.com/itsecd/academic-fundamentals/files/15178704/Lab2_3.pdf)
[tex and cls file.zip](https://github.com/itsecd/academic-fundamentals/files/15178711/tex.and.cls.file.zip)

2024-05-03 05:10 UTC, Olga1140 requested changes
1 3 пункт задания не выполнен
2 В задании написано, что должно быть 3-5 не очень легких формул

2024-05-03 05:10 UTC, Olga1140 commented on main.tex
> +\hspace*{1.5mm}where f is a “random-like” function taking integer values in a range R of mean m
Добавьте "где..." в строку с самой формулой. f должен быть курсивым

2024-05-05 16:29 UTC, only-hell commented
Исправил

2024-05-06 17:02 UTC, Olga1140 commented on main.tex
> +\hspace*{1.5mm}where f is a “random-like” function taking integer values in a range R of mean m
Это не выполнено

2024-05-06 17:04 UTC, Olga1140 requested changes
3 пункт так и не выполнен
Одно замечание в комментариях

Формулы стали сложнее, молодцы, доделывайте

2024-05-06 17:04 UTC, Olga1140 commented on oni2-ИСПРАВЛЕНИЕ1.tex
> +$$f(x) = \int_{-\infty}^{\infty} \hat{f}(\xi)\,e^{2 \pi i \xi x} \,d\xi = \sum_{n=-\infty}^{\infty} f_n\,e^{2 \pi i n x / T},$$ where $\hat{f}(\xi) = \int_{-\infty}^{\infty} f(x) e^{-2 \pi i \xi x} \
Сделайте так, чтобы пределы интегрирования были не справа от интеграла, а сверху и снизу

2024-05-08 18:44 UTC, Olga1140 commented
Ну я вообще изменений не увидела

2024-05-08 18:47 UTC, Olga1140 commented
Вам нужно прислать архив со всеми изменениями, про которые я вам писала

2024-05-09 19:56 UTC, only-hell commented
Ввиду того что мы меняем стиль документа мы теряем возможность создания оглавления. Старый тип - артикл, новый тип - биометрика

2024-05-10 06:20 UTC, only-hell commented
Помимо этого у нас поменялись шрифты, заголовки были слева стали по центру

2024-05-16 04:17 UTC, closed without merging