6112 Lab2L Николаев Мась
itsecd/academic-fundamentals pull request #167
Opened 2024-04-30 19:07 UTC by ilyanikoniko

2024-05-03 05:21 UTC, Olga1140 requested changes
Проверьте файлы, которые вы прикрепили

2024-05-03 11:10 UTC, ilyanikoniko commented
Файлы BSR.zip и sample-acmlarge.tex соответствуют заданию с Latex

2024-05-05 10:52 UTC, Olga1140 commented
Хорошо, если sample-acmlarge.tex соответствует заданию, то я могу сказать, что вы ничего не делали, так как он пустой.
Если я попросила проверить файлы, значит, я увидела там что-то не то. Мне нужен tex файл и zip архив с файлами для нормальной компиляции, если в архиве есть что-то лишнее, уберите это

2024-05-06 16:44 UTC, Olga1140 commented
Файл sample-acmlarge.tex в github все еще пустой

2024-05-06 16:54 UTC, ilyanikoniko commented
sample-acmlarge1.tex и lab3.zip окончательный вариант. Нашли проблему, теперь файл не пустой

2024-05-07 09:59 UTC, Olga1140 requested changes
1 3 пункт задания не выполнен. Вам надо применить 2 cls файла, строки для подключения одного из них закомментируйте
2 У вас вторая формула очень легкая, а третья похожа на четвертую. Добавьте что-то еще

2024-05-07 09:59 UTC, Olga1140 commented on sample-acmlarge1.tex
> +d_{GDCA}(y_1, y_2) = \sqrt{\sum_{i=1}^{n} f(\mu_i, \frac{n}{N}, h) (y_{1,i} - y_{2,i})^2},
Скобки слишком маленькие

2024-05-07 09:59 UTC, Olga1140 commented on sample-acmlarge1.tex
> +where $f$ is a monotonic function of $\mu_i$’s, and also a function of the dimension/size ratio $\frac{n}{N}$ and the
Штрих не так записывается

2024-05-07 09:59 UTC, Olga1140 commented on sample-acmlarge1.tex
> +where $S_b$ and $S_w$ are the within-class and between class scatter matrices respectively.
Добавьте "где..." в строку с самой формулой

2024-05-08 06:16 UTC, Olga1140 commented
Штрих можно записать намного легче '.

2024-05-08 06:16 UTC, Olga1140 approved these changes

2024-05-16 04:17 UTC, closed without merging