6112 Lab2L Loshmankin Dubrovin
itsecd/academic-fundamentals pull request #168
Opened 2024-05-01 10:57 UTC by Jupiter0303

2024-05-04 18:24 UTC, Olga1140 requested changes
1 Не выполнен 3 пункт задания
2 Параметры и переменные должны быть окружены долларами, так они будут отличаться от остального текста

2024-05-04 18:24 UTC, Olga1140 commented on main.txt
> +where $\varepsilon$|= p means that p holds on $\varepsilon$.
Добавьте "где..." в строку с самой формулой. Проверьте то, что написано после "где". Так должно быть?

2024-05-04 18:24 UTC, Olga1140 commented on main.txt
> +     b_k = v_k^{-1}(\sum_{i=1}^{k-1}b_iv_i - d\sum_{i=1}a_iu_i. \label{2}
Посмотрите, как записана формула. Что тут не так?

2024-05-04 18:24 UTC, Olga1140 commented on main.txt
> +where $u_i=logU_i$ and $V_i=logV_i$.
Логарифмы записывают не курсивым

2024-05-04 18:24 UTC, Olga1140 commented on main.txt
> +    E(x)\otimes E(y) = E(x \oplus y) \Rightarrow \prod_{k=1}^nE(b_i)=E(\sum_{i=1}^nb_i).\label{3}
Слишком маленькие скобки

2024-05-06 13:18 UTC, Jupiter0303 commented
[lab2.3 (1).zip](https://github.com/itsecd/academic-fundamentals/files/15221076/lab2.3.1.zip)
[lab2.3_second_cls (1).zip](https://github.com/itsecd/academic-fundamentals/files/15221077/lab2.3_second_cls.1.zip)
[main.txt](https://github.com/itsecd/academic-fundamentals/files/15221078/main.txt)

2024-05-06 14:30 UTC, Jupiter0303 commented
Исправлено

2024-05-07 08:57 UTC, Olga1140 requested changes
1 Вы применили только 1 шаблон, добавьте в тот же tex файл второй шаблон, строки для подключения первого шаблона закомментируйте
2 Замечание про параметры не выполнено
3 Замечание по поводу "где..." не выполнено
4 Вторая формула записалась так, как вы и планировали?

2024-05-08 19:15 UTC, Olga1140 commented
1 Оба стиля компилируются с ошибками, возможно вы не взяли из примеров строки, которые необходимы для работы шаблонов
2 В формулах маленькие скобки
3 Логарифмы записываются не так

2024-05-09 08:49 UTC, Jupiter0303 commented
Изменения внесены

2024-05-09 14:10 UTC, Olga1140 commented
К сожалению, вы внесли изменения слишком поздно

2024-05-16 04:17 UTC, closed without merging