6113 2L Азарова Баранова
itsecd/academic-fundamentals pull request #175
Opened 2024-05-01 18:23 UTC by venikkk

2024-05-05 04:20 UTC, Olga1140 requested changes
Вам в дискорде написали, что нужно прикреплять не только архив, но и отдельный tex файл

1 Не выполнен 3 пункт задания
2 Ограничения у суммы принято записывать не справа, а сверху и снизу

2024-05-08 15:17 UTC, venikkk commented
Добрый вечер, исправила ошибки.
[article.zip](https://github.com/itsecd/academic-fundamentals/files/15250878/article.zip)
[main.zip](https://github.com/itsecd/academic-fundamentals/files/15250879/main.zip)

2024-05-09 11:35 UTC, Olga1140 commented
Как прикреплять файлы, вы так и не поняли

Изменения с ограничениями увидела, первое замечание вы не выполнили, поэтому лабораторную зачесть я не могу

2024-05-09 12:13 UTC, venikkk commented
> Как прикреплять файлы, вы так и не поняли
> 
> Изменения с ограничениями увидела, первое замечание вы не выполнили, поэтому лабораторную зачесть я не могу

Здравствуйте, а есть какая-то другая возможность исправить файлы? Я подключила второй cls-файл
Можно я скину скриншоты?

2024-05-09 12:17 UTC, Olga1140 commented
Здравствуйте. Не поняла этот вопрос: а есть какая-то другая возможность исправить файлы?

2024-05-09 12:20 UTC, venikkk commented
> Здравствуйте. Не поняла этот вопрос: а есть какая-то другая возможность исправить файлы?

просто в репозиторий уже нельзя загрузить в Files changed

2024-05-09 12:23 UTC, venikkk reviewed
![1](https://github.com/itsecd/academic-fundamentals/assets/160824727/2278981b-efbf-4a2f-a980-c9d1cf76f91b)
![2](https://github.com/itsecd/academic-fundamentals/assets/160824727/376d197d-5da7-41bb-a8cc-5875020e4983)
![3](https://github.com/itsecd/academic-fundamentals/assets/160824727/1ad2deaa-54dd-41bd-82a8-9d6a69fdd7de)

2024-05-09 12:24 UTC, Olga1140 commented
Остальные как-то меняли файлы, но я помочь с этим не могу, к сожалению, насколько я поняла, вам давали инструкцию какую-то по использованию github.

Не зачла я вам работу не из-за того, что вы не прочитали сразу, как правильно подгружать файлы, а из-за того, что вы выполнили не все

2024-05-09 12:25 UTC, Olga1140 commented
Не поняла, зачем вы прислали картинки

2024-05-09 12:26 UTC, venikkk commented
> Не поняла, зачем вы прислали картинки
пыталась загрузить их в Files Changes
 могу ли получить зачет по этой лабораторной или уже нет? 
я подключила второй cls-файл

2024-05-09 12:43 UTC, Olga1140 commented
устанавливается новый дедлайн - 9 мая. До этой даты можно отправлять в PR и вносить правки

Сегодня уже не "до этой даты", поэтому нет

2024-05-09 12:44 UTC, Olga1140 commented
Вы же не сегодня узнали про второй шаблон?

2024-05-09 12:44 UTC, Olga1140 commented
Я сейчас посмотрела, вы и первый шаблон не подключили

2024-05-09 13:36 UTC, venikkk commented
> устанавливается новый дедлайн - 9 мая. До этой даты можно отправлять в PR и вносить правки
> 
> Сегодня уже не "до этой даты", поэтому нет

Хорошо, спасибо

2024-05-16 04:17 UTC, closed without merging