6114 Lab2L Непряхин
itsecd/academic-fundamentals pull request #178
Opened 2024-05-04 19:25 UTC by nprkhn

2024-05-06 15:10 UTC, Olga1140 requested changes
1 Нет второго шаблона. Добавьте строки для переключения шаблона в уже имеющийся файл и закомментируйте их
2 Если в тексте есть параметры и переменные, их выделяют долларами для того, чтобы они отличались от основного текста
3 Сколько у Вас формул? Сколько нужно?

2024-05-06 15:10 UTC, Olga1140 commented on main.tex
> +        max(\left | E_{A,t} \right |, k) \text{ otherwise}
max должен быть написан не курсивым

2024-05-07 19:28 UTC, nprkhn commented
Здравствуйте! Внес изменения

2024-05-08 17:06 UTC, Olga1140 commented
Удаляйте архивы, которые уже не нужны

2024-05-08 17:11 UTC, Olga1140 commented
Какие строки нужно закомментировать для того, чтобы переключить шаблон на acmart?
2 пункт из моего первого замечания

2024-05-08 17:37 UTC, nprkhn commented
%\documentclass[]{acmart}
\documentclass[]{seismica}
Для переключения шаблона нужно раскомментировать первую строку и закомментировать вторую строку

2024-05-09 12:48 UTC, Olga1140 commented
У вас вылезают ошибки при переключении на seismica? У меня да
2 пункт из моего первого замечания вы игнорируете уже не в первый раз

Учитывая эти замечания, работу я зачесть не могу

2024-05-09 16:43 UTC, nprkhn commented
Meyerson-Approax & possible, but only for small $k$ using suppression alone & O(klog$K$) of optimal
when $t$ is suppressed by $H$
$g$ is the number of groups in k-paritition;
$k$ is a result of observing attributes
     Я же проставил везде в тексте знак $.
Ошибка вылезает в строке с командой /section, он пишет, что не знает эту команду

2024-05-16 04:17 UTC, closed without merging