6113 Lab2L Пименов и Черкашин
itsecd/academic-fundamentals pull request #183
Opened 2024-05-08 13:08 UTC by DANILA21-3

2024-05-08 19:08 UTC, Olga1140 requested changes
1 Первые две формулы похожи, добавьте что-то еще
2 Если в тексте есть параметры и переменные, их окружают долларами
3 При переключении на второй стиль вылезают ошибки

2024-05-08 19:08 UTC, Olga1140 commented on main.tex
> +where
Добавьте "где" в строку с формулой

2024-05-08 19:08 UTC, Olga1140 commented on main.tex
> +P(u,v)=\frac{\sum_{N}^{i=1}d_{i}^{-2}*t_i}{\sum_{N}^{i=1}d_{i}^{-2}},
Ограничения принято указывать не справа от суммы, а сверху и снизу

2024-05-09 18:08 UTC, DANILA21-3 reviewed
Правки внесены
[LaTeX.zip](https://github.com/itsecd/academic-fundamentals/files/15266015/LaTeX.zip)

2024-05-16 04:17 UTC, closed without merging