6114 Голунов Петров Lab2L
itsecd/academic-fundamentals pull request #185
Opened 2024-05-08 16:37 UTC by yui1337

Полностью переписанная версия с 2 проверенно работающими стилями. Один из них закомменчен в начале.

2024-05-09 12:03 UTC, Olga1140 requested changes
1 Оба шаблона работают с ошибками
2 Замечание про переменные и параметры не исправлено
3 Замечание про "где..." не исправлено
4 Не про все формулы можно сказать, что они сложные (или хотя бы не очень легкие)

Учитывая все замечания, работу я вам не засчитываю

2024-05-09 15:14 UTC, yui1337 commented
![image](https://github.com/itsecd/academic-fundamentals/assets/159301886/05f6a5eb-2bd1-4e82-9c38-58bfd57c6106)
В книге "LaTeX по-русски" формулы описываются именно так, как у нас. Добавление "где..." внутрь displaymath вызывает кучу ошибок или неправильное отображение текста(номер формулы после текста "где...", либо сам текст начинает выглядеть так, будто окружен долларами), а в лекциях вы об этом ничего не говорили. Поэтому прошу уточнить, как именно вы хотите добавить текст "где..." внутрь displaymath (\begin
[6114 Golunov Petrov Lab2L try3.zip](https://github.com/itsecd/academic-fundamentals/files/15263975/6114.Golunov.Petrov.Lab2L.try3.zip)
{equation ... \end{equation}).

Все остальные замечания исправлены. Ошибок при использовании обоих стилей не возникает.

2024-05-09 15:21 UTC, Olga1140 commented
\text{where}, в лекции про это было

2024-05-09 15:22 UTC, Olga1140 commented
Попробуйте, будет ошибка вылезать?

2024-05-09 16:16 UTC, Olga1140 commented
Потому что пояснение большое, но текст при этом выводится не курсивым
Я увидела параметры, их нужно брать в доллары, чтобы они отличались от остального текста (это я вам писала уже несколько раз)

2024-05-09 16:43 UTC, Olga1140 commented
Посмотрите, что у вас написано после where

2024-05-09 16:43 UTC, Olga1140 commented
a и b вы должны были окружить долларами, запомните это на будущее

2024-05-09 16:45 UTC, Olga1140 commented
На всякий случай уточню, сейчас вы уже можете не присылать мне никакие изменения, я уже написала вам, что работу я не засчитываю, так как последние изменения вам разрешили прислать ДО 9 мая

2024-05-09 16:48 UTC, yui1337 commented
"Для лабы 2L (часть по LaTeX) устанавливается новый дедлайн - 9 мая. До этой даты можно отправлять в PR и вносить правки по требованию преподавателя. _**После**_ этой даты всё заморозится. Все, кто не успеет сдать, получат прочерки по этой лабе."
9 мая - не после 9 мая.
 
[6114 Golunov Petrov Lab2L try 5.zip](https://github.com/itsecd/academic-fundamentals/files/15265063/6114.Golunov.Petrov.Lab2L.try.5.zip)
a и b были окружены долларами.

2024-05-09 16:50 UTC, Olga1140 commented
Для лабы 2L (часть по LaTeX) устанавливается новый дедлайн - 9 мая. ДО этой даты можно отправлять в PR и вносить правки по требованию преподавателя.

2024-05-09 16:52 UTC, yui1337 commented
Мое мнение может ничего не стоить, но мне кажется, что Виктор Андреевич забыл добавить слово включительно.

2024-05-09 16:54 UTC, Olga1140 commented
Следовательно, вы не должны были считать, что это включительно

2024-05-09 17:10 UTC, yui1337 commented
Не хочется спорить о том, кто, что и как посчитал. Я задал вопрос Виктору Андреевичу.

2024-05-10 00:27 UTC, yui1337 commented
![Screenshot_20240510-042525](https://github.com/itsecd/academic-fundamentals/assets/159301886/854e9260-7ce8-4da5-b7ad-3225aeac841d)

2024-05-16 04:17 UTC, closed without merging