6113 Lab2M Никишин Попов
itsecd/academic-fundamentals pull request #208
Opened 2024-05-17 16:20 UTC by h0shi-tech

2024-05-18 06:59 UTC, vicanfed requested changes
Мне кажется, вы не показывали работу преподавателю в классе, поскольку там куча ошибок.

2024-05-19 15:23 UTC, h0shi-tech commented
Извините, кажется мы что-то не то отправили

2024-05-20 14:38 UTC, vicanfed commented
Нет меток таблиц и рисунков и ссылок на них, формулы неправильно набраны и по сути бессмысленны.

2024-05-25 13:14 UTC, h0shi-tech commented
[2_1.docx](https://github.com/itsecd/academic-fundamentals/files/15443587/2_1.docx)

2024-05-25 13:15 UTC, h0shi-tech commented
Исправил метки таблиц, рисунков и добавил ссылки на них. Формулы набрал по новому

2024-05-27 16:51 UTC, h0shi-tech commented
Да, изначальные правки внесли по указу преподавателя
[2_1 (Исправлено).docx](https://github.com/itsecd/academic-fundamentals/files/15458334/2_1.docx)

2024-05-28 05:44 UTC, vicanfed commented
Пока у преподавателя в классе есть хоть одно замечание, работу на PR вы отправлять не должны.
Я и так уже два раза проверял вашу работу, тогда как по правилам вы должны взаимодействовать с преподавателем в классе.

2024-05-30 06:51 UTC, h0shi-tech commented
Преподаватель сказал отправить работу в Pull Request. Последние правки актуальные

2024-05-30 07:45 UTC, h0shi-tech commented
[2_2.docx](https://github.com/itsecd/academic-fundamentals/files/15495491/2_2.docx)
[2_1.docx](https://github.com/itsecd/academic-fundamentals/files/15495492/2_1.docx)
Исправили все по указу преподавателя

2024-05-30 12:49 UTC, closed without merging