6112 Lab3L Дубровин Лошманкин
itsecd/academic-fundamentals pull request #257
Opened 2024-06-23 13:25 UTC by Jupiter0303

[Dubrovin 6112 beamer.pdf](https://github.com/user-attachments/files/15944741/Dubrovin.6112.beamer.pdf)
[main.txt](https://github.com/user-attachments/files/15944742/main.txt)
[main handout.txt](https://github.com/user-attachments/files/15944743/main.handout.txt)
[Dubrovin 6112 beamer handout.pdf](https://github.com/user-attachments/files/15944744/Dubrovin.6112.beamer.handout.pdf)
[Dubrovin 6112 beamer handout.zip](https://github.com/user-attachments/files/15944745/Dubrovin.6112.beamer.handout.zip)
[Dubrovin 6112 beamer.zip](https://github.com/user-attachments/files/15944746/Dubrovin.6112.beamer.zip)

2024-06-25 12:16 UTC, vicanfed requested changes
Не выполнены два из семи ключевых требований, указанных в задании.
Также есть мелкие замечания

2024-06-25 12:16 UTC, vicanfed commented on main handout.tex
> +        \item Кажется, что методы электронного голосования в скорем \alert{заменят} традиционные.\newline
Зачем?

2024-06-25 12:16 UTC, vicanfed commented on main handout.tex
> +
Зачем нам пустые строки?

2024-06-26 18:38 UTC, Jupiter0303 commented
Были убраны лишние "\newline", исправлены первый (слайд эксперимента) и седьмой пунк (преамбула), если конечно именно эти пункты были не выполнены.

[main.txt](https://github.com/user-attachments/files/15993896/main.txt)
[main (handout).txt](https://github.com/user-attachments/files/15993898/main.handout.txt)
[Электронные машины для голосования по сравнению с традиционными методами.pdf](https://github.com/user-attachments/files/15993899/default.pdf)
[Электронные машины для голосования по сравнению с традиционными методами (handout).pdf](https://github.com/user-attachments/files/15993900/handout.pdf)
[Электронные машины для голосования по сравнению с традиционными методами (handout).zip](https://github.com/user-attachments/files/15993901/handout.zip)
[Электронные машины для голосования по сравнению с традиционными методами.zip](https://github.com/user-attachments/files/15993902/default.zip)

2024-06-28 07:47 UTC, vicanfed commented
Почему мне приходится учить людей читать?
Почему это не является базовым умением каждого студента уже почти второго курса?...

Перед вами задание на лабу. От и до.
Найдите в этом списке то, что вы не выполнили.

![image](https://github.com/itsecd/academic-fundamentals/assets/86360217/5d13c0ce-67c7-4130-9562-72c95ea6e8ab)

2024-06-28 07:48 UTC, vicanfed requested changes
Почему мне приходится учить людей читать?
Почему это не является базовым умением каждого студента уже почти второго курса?...

Перед вами задание на лабу. От и до.
Найдите в этом списке то, что вы не выполнили.

![image](https://github.com/itsecd/academic-fundamentals/assets/86360217/5d13c0ce-67c7-4130-9562-72c95ea6e8ab)

2024-06-28 11:13 UTC, Jupiter0303 commented
Я знаю, что нужно читать задание, Сергиенко вам бы абы что прислал, если бы я ему не сказал задание прочесть. Я читал и проверял эти пункты десятки раз. Простите, что я такой непонимающий.
на всякий случай:
1. itemize[<+->] используется в секции эксперимента.
2. Слайд содержания имеется.
3. \alert активно используется.
4. Блочное окружение используется в секции обсуждения и заключения.
5. есть слайды с таблицей и рисунком.
6. columns также активно используется.
7. handout версия имеется, в преамбуле указано, что это handout, все вышеперечисленные пункты также содержатся в handout версии.

[Электронные машины для голосования по сравнению с традиционными методами (handout).zip](https://github.com/user-attachments/files/16028502/handout.zip)
[main.txt](https://github.com/user-attachments/files/16028503/main.txt)
[main (handout).txt](https://github.com/user-attachments/files/16028504/main.handout.txt)
[Электронные машины для голосования по сравнению с традиционными методами (handout).pdf](https://github.com/user-attachments/files/16028505/handout.pdf)
[Электронные машины для голосования по сравнению с традиционными методами.zip](https://github.com/user-attachments/files/16028506/default.zip)
[Электронные машины для голосования по сравнению с традиционными методами.pdf](https://github.com/user-attachments/files/16028507/default.pdf)

2024-06-28 11:23 UTC, vicanfed approved these changes
До этого динамического контента не было, теперь появился.

с columns тоже такое дело: column у вас есть, но оборачивающего окружения columns нигде нет. Поэтому я не уверен, что у вас это работало бы вне Overleaf. Тем не менее, раз результат положительный засчитываю.

2024-09-08 09:04 UTC, closed without merging