6112 Lab2L Фоменко
itsecd/academic-fundamentals pull request #259
Opened 2024-09-08 15:38 UTC by YaroslavFomenko

2024-09-16 07:03 UTC, Olga1140 requested changes
Добрый день!

У меня программа выдает ошибки, у Вас их нет?

1. Если в тексте встречаются переменные и парамтеры, их надо выделять долларами.
2. where после второй формулы добавьте в строку с самой формулой.
3. Двух стилей я не увидела
4. Оглавления я не увидела
5. Заголовков двух уровней тоже

2024-09-19 17:11 UTC, YaroslavFomenko commented
[Lab2L 1 style.zip](https://github.com/user-attachments/files/17063372/Lab2L.1.style.zip)
[Lab2L 2 style.zip](https://github.com/user-attachments/files/17063373/Lab2L.2.style.zip)
[Lab2L.txt](https://github.com/user-attachments/files/17063374/Lab2L.txt)
все 5 пунктов исправил,ошибки у меня не отображаются,все работает

2024-09-20 06:45 UTC, Olga1140 commented
Ошибки у меня так и вылезают. Запустите код у себя и пришлите скрин.
Изменений по первому пункту не увидела. Заметила, что в одном месте у Вас написано хо, уо, там 0 должен быть как индекс?
where должен быть написан не курсивным шрифтом, он должен выглядеть как обычный текст.

2024-09-20 13:23 UTC, YaroslavFomenko commented
[Lab2L 1 style.zip](https://github.com/user-attachments/files/17075769/Lab2L.1.style.zip)
[Lab2L 2 style.zip](https://github.com/user-attachments/files/17075770/Lab2L.2.style.zip)
[Lab2L.txt](https://github.com/user-attachments/files/17075771/Lab2L.txt)
![Снимок экрана (2)](https://github.com/user-attachments/assets/b6def032-bdd9-491f-b76b-025d9099bfb0)
Вот есть одна ошибка,но она никак не связана с моим кодом,where исправил,а насчет первого пункта я вроде несколько раз проверил все переменные у меня в $

2024-09-21 09:09 UTC, Olga1140 commented
Ошибок быть не должно, возможно, Вы убрали/добавили строки, что не подходит выбранному стилю

2024-09-21 19:07 UTC, YaroslavFomenko commented
[Lab2L 1 style.zip](https://github.com/user-attachments/files/17085480/Lab2L.1.style.zip)
[Lab2L 2 style.zip](https://github.com/user-attachments/files/17085481/Lab2L.2.style.zip)
[Lab2L.txt](https://github.com/user-attachments/files/17085482/Lab2L.txt)
Все исправил,оба стиля без ошибок

2024-09-22 09:26 UTC, Olga1140 commented
Какие cls файлы Вы использовали? Также я все еще жду, когда Вы все переменные и параметры в тексте окружите долларами

2024-09-22 09:44 UTC, YaroslavFomenko commented
можете ,пожалуйста, указать,где у меня переменные не заключены в доллары

2024-09-22 10:01 UTC, Olga1140 commented
Вы прикрепляли tex файл? Нет. Вам говорили прикреплять tex файл отдельно, чтобы можно было что-то указать в коде. Поэтому ищите самостоятельно, тем более работа не такая уж большая, можно просмотреть все достаточно быстро

2024-09-22 10:30 UTC, YaroslavFomenko commented
[Lab2L 1 style.zip](https://github.com/user-attachments/files/17089214/Lab2L.1.style.zip)
[Lab2L 2 style.zip](https://github.com/user-attachments/files/17089215/Lab2L.2.style.zip)
Я нашел x и A,B,C,D,E не заключенные в доллары. В первом стиле optica-article.cls,а во втором oup-authoring-template.cls

2024-09-22 18:04 UTC, Olga1140 commented
В строке с х, у Вас стоят у и р. Про хо и уо в 4 пункте я Вам уже писала. Старайтесь выполнять все замечания преподавателей сразу, а не по одному присылать

2024-09-22 18:05 UTC, Olga1140 approved these changes
Некоторые параметры и переменные все еще неверно оформлены, но, надеюсь, Вы это сможете сами исправить. Работу засчитываю

2024-09-25 09:01 UTC, closed without merging