6111 Lab3L Магомедагаев
itsecd/academic-fundamentals pull request #260
Opened 2024-09-09 11:25 UTC by anzorcode05

[3L beamer(handout).zip](https://github.com/user-attachments/files/16929702/3L.beamer.handout.zip)
[3L beamer.zip](https://github.com/user-attachments/files/16929705/3L.beamer.zip)
[3L(handout).txt](https://github.com/user-attachments/files/16929706/3L.handout.txt)
[3L.txt](https://github.com/user-attachments/files/16929707/3L.txt)
[3L_beamer(1).pdf](https://github.com/user-attachments/files/16929708/3L_beamer.1.pdf)
[3L_beamer(handout).pdf](https://github.com/user-attachments/files/16929710/3L_beamer.handout.pdf)

2024-09-16 08:06 UTC, Olga1140 requested changes
Добрый день!

У меня не работает этот код. У Вас работает? Пришлите скрин экрана, если работает

2024-09-19 15:28 UTC, anzorcode05 commented
Здравствуйте,да конечно ,вот мой скриншот,это версия handout если что могу и первоначальный вариант отправить 
![image](https://github.com/user-attachments/assets/79ae27f6-56b6-4c50-bfd0-f12f10e94696)

2024-09-20 05:19 UTC, Olga1140 commented
Я сейчас еще раз попробовала запустить, не работает вообще, иногда с ошибками, но что-то выдает. Проверьте, тот ли Вы архив прислали

2024-09-22 09:54 UTC, anzorcode05 commented
запустил архив,все работает ,там изображение как по заданию,и main файл попробуйте скопировать код с txt файла и вставить в beamer у меня все работает

2024-09-22 09:56 UTC, anzorcode05 commented
[beamer anzor.zip](https://github.com/user-attachments/files/17089064/beamer.anzor.zip)
попробуйте эту версию

2024-09-22 17:57 UTC, Olga1140 commented
Вы, видимо, поменяли у себя настройки, поэтому у Вас этот код работал, а у меня нет. Вы выполнили самый первый пункт задания? Остальное я нашла и зачла

2024-09-22 18:49 UTC, anzorcode05 commented
вы про пример динамического изменения содержимого фрейма ? у меня это осуществляется  через разделение контента на секции и фреймы, которые представляют разные части презентации. В частности, динамическое обновление происходит через использование команд **_\begin{frame}_** и \end{frame}, которые создают новые слайды для каждой секции.Это своего рода отдельное изменение фрейма просто про него не упомянуто (в примерах к этому пункту)

2024-09-23 12:57 UTC, Olga1140 commented
Я правильно поняла, Вы считаете изменением содержимого фрейма создание новых фреймов?

2024-09-24 00:43 UTC, anzorcode05 commented
не совсем.прошу прощения не правильно выразил свою мысль хотел написать про создание фреймов,динамическое изменение фреймов у меня в этом файле с использованием **\item<>** которая заставляет элементы списка появляться по очереди на каждом нажатии клавиши.Вот переделанный вариант 
[beamer_anzor (1).pdf](https://github.com/user-attachments/files/17106311/beamer_anzor.1.pdf)
[beamer anzor (1).zip](https://github.com/user-attachments/files/17106313/beamer.anzor.1.zip)
[beamer.txt](https://github.com/user-attachments/files/17106315/beamer.txt)

2024-09-24 14:46 UTC, Olga1140 approved these changes
Теперь верно

2024-09-25 09:00 UTC, closed without merging