6113 Lab2L Данилюк Железнов
itsecd/academic-fundamentals pull request #261
Opened 2024-09-10 23:09 UTC by SnowDrop163

2024-09-16 08:21 UTC, Olga1140 requested changes
Добрый день!

1. Не увидела cls файлов
2. Пределы интегрирования принято писать не справа, а снизу и сверху
3. Если в тексте встречаются параметры и переменные, их нужно выделять долларами

2024-09-16 17:52 UTC, SnowDrop163 commented
[6113 Lab2L Данилюк Железнов.zip](https://github.com/user-attachments/files/17017378/6113.Lab2L.zip)
[6113 Lab2L Данилюк Железнов.zip](https://github.com/user-attachments/files/17017378/6113.Lab2L.zip)
Исправил вроде бы все ошибки

2024-09-19 19:43 UTC, Olga1140 commented
Добрый вечер, код работает с ошибками. Все остальное засчитано

2024-09-20 14:23 UTC, SnowDrop163 commented
[6113Danilyuk_Zheleznov.zip](https://github.com/user-attachments/files/17076589/6113Danilyuk_Zheleznov.zip)
Ошибок больше никаких не выдает.

2024-09-21 15:14 UTC, Olga1140 approved these changes
Засчитано

2024-09-25 09:02 UTC, closed without merging