6114 Lab 2L Глинтухов
itsecd/academic-fundamentals pull request #268
Opened 2024-09-15 14:08 UTC by GlintuhovYD

[6114 Lab 2L Глинтухов.zip](https://github.com/user-attachments/files/17006017/6114.Lab.2L.zip)
[6114 Lab 2L Глинтухов2.zip](https://github.com/user-attachments/files/17006018/6114.Lab.2L.2.zip)

2024-09-16 12:03 UTC, Olga1140 requested changes
Добрый день!

1 Компилируется с ошибками
2 Переменные и параметры принято записывать в долларах, чтобы они отличались от остального текста
3 Нет нумерованной формулы
4 В разделе 1.2 пояснение к первой формуле добавьте в строку с самой формулой

2024-09-19 17:22 UTC, Olga1140 commented
Добрый вечер, 2 пункт Вы выполняли? Остальное засчитано

2024-09-19 23:35 UTC, GlintuhovYD commented
> Добрый вечер, 2 пункт Вы выполняли? Остальное засчитано

Здравствуйте! 2 пункт выполнил, все возможные переменные заключил в знаки $ в обоих стилях

2024-09-20 06:48 UTC, Olga1140 commented
Я изменений не увидела

2024-09-20 09:04 UTC, GlintuhovYD commented
[6114 Lab 2L Глинтухов2.zip](https://github.com/user-attachments/files/17072726/6114.Lab.2L.2.zip)
[6114 Lab2 2L Глинтухов.zip](https://github.com/user-attachments/files/17072727/6114.Lab2.2L.zip)
все формулы заключил в знаки $

2024-09-21 06:27 UTC, Olga1140 commented
Я Вам не про формулы писала, перечитайте 2 пункт замечаний. С формулами было все нормально

2024-09-21 07:11 UTC, GlintuhovYD commented
[6114 Lab2L Глинтухов2.zip](https://github.com/user-attachments/files/17083230/6114.Lab2L.2.zip)
[6114 Lab2L Глинтухов.zip](https://github.com/user-attachments/files/17083231/6114.Lab2L.zip)
Все переменные в пояснениях к каждой формуле заключил в знаки $, больше в моем тексте переменные нигде не появляются

2024-09-21 15:39 UTC, Olga1140 approved these changes
Засчитано

2024-09-25 08:58 UTC, closed without merging