6113 Lab 2L Сарычев Храмов
itsecd/academic-fundamentals pull request #270
Opened 2024-09-16 19:21 UTC by exhaustion666

2024-09-20 03:56 UTC, Olga1140 requested changes
Добрый день!

1. Пределы интегрирования принято записывать снизу и сверху, а не справа.
2. Добавьте пояснение ко 2 формуле в строку с самой формулой. Переменные и параметры в тексте должны выделяться долларами. Скобки не должны быть меньше выражения в скобках
3. Оба стиля работают с ошибками

2024-09-21 05:48 UTC, exhaustion666 commented
[6113 Lab 2L Sarychev Khramov (3).zip](https://github.com/user-attachments/files/17082993/6113.Lab.2L.Sarychev.Khramov.3.zip)
Исправили.

2024-09-21 15:34 UTC, Olga1140 commented
1 замечание исправлено, Исправьте остальные и только после этого пришлите на проверку

2024-09-21 18:22 UTC, exhaustion666 commented
[6113 Lab 2L Sarychev Khramov (4).zip](https://github.com/user-attachments/files/17085396/6113.Lab.2L.Sarychev.Khramov.4.zip)
Исправили еще раз.

2024-09-22 09:21 UTC, Olga1140 commented
Where должно быть написано не курсивным шрифтом. Я помню, что после второй формулы у вас k=... было в маленьких скобках. Я сделали замечание к ним, а вы их просто убрали. Верните скобки с учетом моего замечания

2024-09-22 09:43 UTC, exhaustion666 commented
[6113 Lab 2L Sarychev Khramov (5).zip](https://github.com/user-attachments/files/17089033/6113.Lab.2L.Sarychev.Khramov.5.zip)
Вернул, where теперь без курсива.

2024-09-22 09:46 UTC, exhaustion666 commented
[6113 Lab 2L Sarychev Khramov (5).zip](https://github.com/user-attachments/files/17089041/6113.Lab.2L.Sarychev.Khramov.5.zip)
Вернул, where теперь без курсива.

2024-09-22 17:40 UTC, Olga1140 commented
А теперь объедините 2 моих замечания по поводу where

2024-09-22 17:43 UTC, exhaustion666 commented
Не совсем понимаю, что надо сделать с ними.

2024-09-23 12:55 UTC, Olga1140 commented
Я не знаю, что тут объяснять, если честно. Если я сказала сделать в строке с формулой, а вы удивляетесь, что я не засчитала, когда вы оттуда убрали

2024-09-23 16:27 UTC, exhaustion666 commented
Вы мне написали с самого начала "Добавьте пояснение ко 2 формуле в строку с самой формулой.", Хорошо, я вроде как вставил это в строку (как это было у других):
![photo_2024-09-22_22-06-31](https://github.com/user-attachments/assets/d9cf4b77-4137-4107-b542-94f64ae5dfb0)
Вы мне пишете "Where должно быть написано не курсивным шрифтом. " Хорошо, чтобы оно не было курсивным шрифтом мне пришлось убрать его из-под знака $$:
![photo_2024-09-22_22-06-18](https://github.com/user-attachments/assets/0203803f-297e-4126-8bae-5221ccccd082)
И поэтому я искренне не понимаю, что от меня требуется с этим замечанием.
Скобки я вернул, сделал их больше, переменные с параметрами у нас вроде как все заключены в $, ошибки у обоих стилей я исправил, остается одно замечание по поводу этого слова. Я пытался сделать это тремя разными способами (причем мне пришлось смотреть как это реализовано у других), но никакой из этих не засчитывается, и поэтому я спрашиваю, что мне надо с ним сделать.

2024-09-23 16:32 UTC, Olga1140 commented
Хорошо, чтобы оно не было курсивным шрифтом мне пришлось убрать его из-под знака $$
Видимо, можно убрать курсивный шрифт, не убирая where из-под знака $$. Об этом говорилось в лекции. Это задание я давала всем, у всех людей, которые получили зачет, получилось это сделать

2024-09-23 16:33 UTC, exhaustion666 commented
Хорошо, сейчас исправлю.

2024-09-23 16:38 UTC, exhaustion666 commented
[Uploading 6113.Lab.2L.Sarychev.Khramov.(6).zip…]()

2024-09-23 16:39 UTC, exhaustion666 commented
[6113.Lab.2L.Sarychev.Khramov.(6).zip](https://github.com/user-attachments/files/17100992/6113.Lab.2L.Sarychev.Khramov.6.zip)

2024-09-24 14:18 UTC, Olga1140 approved these changes

2024-09-25 08:59 UTC, closed without merging