6114 Lab 2L Вершинин Калимов
itsecd/academic-fundamentals pull request #272
Opened 2024-09-17 21:13 UTC by VershininVadim

2024-09-20 05:12 UTC, Olga1140 requested changes
Добрый день, а что Вы прикрепили?

2024-09-20 12:30 UTC, VershininVadim commented
[CUP_Data_Template__3_ (1).pdf](https://github.com/user-attachments/files/17075164/CUP_Data_Template__3_.1.pdf)
Мы забыли прикрепить еще один файл, но если что -то поломалось вы сообщите и мы снова отправим весь zip файл на проверку

2024-09-20 12:32 UTC, VershininVadim commented
На всякий случай я отправлю снова весь zip файл со всей лабой
[Lab 2L Kalimov Verhinin.zip](https://github.com/user-attachments/files/17075203/Lab.2L.Kalimov.Verhinin.zip)

2024-09-21 09:07 UTC, Olga1140 commented
Нет нумерованной формулы
Код работает с ошибками
Должно было быть 2 стиля, а не 1
В последней формуле where добавьте в строку с самой формулой
Нет оглавления

2024-09-21 13:09 UTC, VershininVadim commented
[Lab 2L переделанная.zip](https://github.com/user-attachments/files/17084131/Lab.2L.zip)
Это переделанная работа, исправили вроде

2024-09-22 09:16 UTC, Olga1140 commented
Первый стиль работает с ошибками. В какой-то формуле добавьте where в строку с самой формулой

2024-09-22 10:50 UTC, VershininVadim commented
[Latex Lab 2L переделанная (2).zip](https://github.com/user-attachments/files/17089288/Latex.Lab.2L.2.zip)
вроде исправили, надеемся что все правильно

2024-09-22 18:11 UTC, Olga1140 commented
Теперь у меня второй стиль с ошибками работает. Все строки я закоментировала, которые у вас отмечены

2024-09-22 20:21 UTC, VershininVadim commented
[Стиль тезис.zip](https://github.com/user-attachments/files/17091207/default.zip)
[Стиль life.zip](https://github.com/user-attachments/files/17091208/life.zip)
вроде все исправили

2024-09-23 16:18 UTC, Olga1140 approved these changes
Засчитано

2024-09-25 08:49 UTC, closed without merging