6113 Lab2M Danilyuk Zheleznov
itsecd/academic-fundamentals pull request #74
Opened 2024-04-04 07:03 UTC by SnowDrop163

6113_DanilyUK_ZheleznOV

2024-04-08 19:39 UTC, vicanfed requested changes
Стили либо не используются, либо используются не те. При применении стиля абзаца форматирование слетает почти везде. Всё пока очень далеко от нормы.

2024-05-08 16:08 UTC, SnowDrop163 commented
[6113_DanilyUK_ZheleznOV-1я часть.docx](https://github.com/itsecd/academic-fundamentals/files/15251693/6113_DanilyUK_ZheleznOV-1.docx)
[6113_DanilyUK_ZheleznOV-2я часть.docx](https://github.com/itsecd/academic-fundamentals/files/15251694/6113_DanilyUK_ZheleznOV-2.docx)
Исправили ошибки

2024-05-09 04:52 UTC, vicanfed commented
1. Вам нужно было устранить замечания и показать преподавателю в классе. Для этого было 2 занятия. Чтобы не лишать вас шансов, всё же посмотрел.
2. По части 1 замечания в файле 
[файле](https://github.com/itsecd/academic-fundamentals/files/15257699/6113_DanilyUK_ZheleznOV-1.docx)
3. По части 2 замечание одно глобальное. И это замечание я вам писал месяц назад: "При применении стиля абзаца форматирование слетает почти везде."

2024-05-09 17:22 UTC, SnowDrop163 commented
[6113_DanilyUK_ZheleznOV_1-я часть.docx](https://github.com/itsecd/academic-fundamentals/files/15265415/6113_DanilyUK_ZheleznOV_1-.docx)
[6113_DanilyUK_ZheleznOV_2-я часть.docx](https://github.com/itsecd/academic-fundamentals/files/15265416/6113_DanilyUK_ZheleznOV_2-.docx)
Все, что вы сказали, мы исправили, вроде бы.

2024-05-09 20:20 UTC, vicanfed commented
Нет, хорошенького понемногу.
Правила есть правила. Вы должны показать исправления на занятии. Если всё ОК, то вам зачтут лабу.

2024-05-30 12:49 UTC, closed without merging