6114 Lab2M Голунов Петров
itsecd/academic-fundamentals pull request #78
Opened 2024-04-04 10:23 UTC by yui1337

2024-04-08 20:18 UTC, vicanfed requested changes
Требуется повторная отправка после исправлений.

1. 
[лаба они готовая_review.docx](https://github.com/itsecd/academic-fundamentals/files/14910565/_review.docx)
2. Изменения не внесены в стили.

2024-04-11 08:50 UTC, yui1337 commented
[!ОНИ 1 часть 2 лаба испр.docx](https://github.com/itsecd/academic-fundamentals/files/14943741/1.2.docx)
Исправленная 1 часть. 

Хочется уточнить, что вы имели ввиду под "Изменения не внесены в стили"?

2024-04-17 19:26 UTC, vicanfed requested changes
Небольшие изменения по первой части
[1.2.docx](https://github.com/itsecd/academic-fundamentals/files/15016023/1.2.docx)

По второй - все визуальные изменения должны быть реализованы на уровне стилей, а не отдельных фрагментов текста. Если применить к абзацу стиль, который отображается для данного абзаца, ничего меняться не должно.

2024-04-25 09:18 UTC, vicanfed commented
Все исправления показываем преподавателю в классе

2024-04-25 11:02 UTC, vicanfed requested changes
Покажите исправления преподавателю в классе

2024-04-25 17:13 UTC, yui1337 commented
Преподаватель просмотрел обе части и одобрил.

2024-05-05 14:32 UTC, closed without merging