6111 Lab2L Косакян Иноземцев
itsecd/academic-fundamentals pull request #84
Opened 2024-04-11 05:32 UTC by HermanKosakian

2024-04-13 16:08 UTC, Olga1140 requested changes
Нужно исправить 2 строки, в остальном все хорошо, молодцы!

2024-04-13 16:08 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Напишите "where ..." в одной строке с формулой

2024-04-15 12:16 UTC, HermanKosakian commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
не совсем понял. в коде написать или чтобы в итоговом pdf было в одной строке?

2024-04-15 12:18 UTC, HermanKosakian commented on main (1).tex
> +            $$\phi_i(x)=\frac{\prod_{j=1}^d\mu_A{_j^i}(x_i)}{\sum_{k=1}^r\prod_{j=1}^d\mu_A{_{j(x_i)}^i}}\eqno(3)\label{f3}$$
я дописал \limits, ограничения теперь снизу и сверху.

2024-04-15 13:16 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Нужно, чтобы в pdf было в одной строке

2024-04-15 13:17 UTC, Olga1140 commented on main (1).tex
> +            $$\phi_i(x)=\frac{\prod_{j=1}^d\mu_A{_j^i}(x_i)}{\sum_{k=1}^r\prod_{j=1}^d\mu_A{_{j(x_i)}^i}}\eqno(3)\label{f3}$$
Отлично

2024-04-17 11:26 UTC, HermanKosakian commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
[lab2_3испр.pdf](https://github.com/itsecd/academic-fundamentals/files/15010099/lab2_3.pdf)
[испр.zip](https://github.com/itsecd/academic-fundamentals/files/15010136/default.zip)
гитхаб не дал прикрепить файл tex, поэтому я его архивировал

2024-04-18 15:28 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Вы на финишной прямой) Параметры, переменные в тексте всегда пишут в долларах, чтобы они от текста отличались. В той строке, что Вы меняли, T, P, ... должны быть написаны одинаково. Понятно?

2024-04-21 13:27 UTC, HermanKosakian commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
$$
 Accuracy=\frac{TP+TN}{FP+FN+TP+TN} \hspace{5mm} where\hspace{2mm} T, F {-} True,  False;\hspace{2mm} N, P {-} Negative, Positive;\eqno(4)\label{f4}
 $$   
вы имели ввиду так сделать?

2024-04-21 14:31 UTC, Olga1140 requested changes

2024-04-21 14:31 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Нет. На самом деле я вам уже написала, как именно нужно сделать. Что я в прошлый раз написала? Параметры, переменные в тексте всегда пишут в долларах, чтобы они от текста отличались.

В том, что вы сделали, курсивым написаны не только переменные и параметры, но и текст. 

Советую вернуть прошлую версию и от нее делать. Здесь дело одной минуты на самом деле

2024-04-25 04:18 UTC, HermanKosakian commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
\begin{displaymath}
                Accuracy=\frac{TP+TN}{FP+FN+TP+TN} \hspace{5mm} \text{where $T, F$ – True,  False;\hspace{2mm} $N, P$ – Negative, Positive;}\eqno(4)\label{f4}
            \end{displaymath}  так?

2024-04-27 05:37 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Да, только я не заметила, как вы нумеруете формулы. Нумерация должна быть автоматической

2024-04-27 05:38 UTC, Olga1140 commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
Доделайте этот момент, после этого я зачту вам работу

2024-04-27 12:26 UTC, HermanKosakian commented on main (1).tex
> +            $$Accuracy=\frac{TP+TN}{FP+FN+TP+TN}\eqno(4)\label{f4}$$
полный файл tex c изменениями. автоматическую нумерацию сделал через equation
[испр2 тех.zip](https://github.com/itsecd/academic-fundamentals/files/15138163/2.zip)

2024-04-27 12:35 UTC, Olga1140 approved these changes

2024-05-16 04:17 UTC, closed without merging