6111 Lab2L Абрамов Горин
itsecd/academic-fundamentals pull request #88
Opened 2024-04-11 07:03 UTC by abramovivan123

2024-04-13 16:17 UTC, Olga1140 requested changes
Для запуска кода мне нужны картинки, которые вы использовали, без них latex выдаст ошибку

2024-04-14 15:44 UTC, abramovivan123 commented
> Для запуска кода мне нужны картинки, которые вы использовали, без них latex выдаст ошибку

![image](https://github.com/itsecd/academic-fundamentals/assets/163386251/a5b0b8a6-cc16-4266-9e41-2630b19b9afc)
![image 1](https://github.com/itsecd/academic-fundamentals/assets/163386251/adc7c88a-a5b6-47c1-aa56-e8bc572771f6)

2024-04-15 14:35 UTC, Olga1140 requested changes
Прикрепите, пожалуйста, картинки в список файлов. Туда, где у вас файлы .tex, .cls ... Вы можете это сделать?

2024-04-16 05:13 UTC, abramovivan123 commented
> Прикрепите, пожалуйста, картинки в список файлов. Туда, где у вас файлы .tex, .cls ... Вы можете это сделать?

А не подскажете, могу ли я это сделать не закрывая данный pull request?

2024-04-16 08:10 UTC, Olga1140 requested changes
Я убрала из кода картинки, но все равно вылезает ошибка. У вас этот код вообще работает? Может, вы еще какие-то файлы прикрепить забыли? Проверьте все еще раз. По поводу того, как прикреплять картинки, помочь не могу, но у кого-то это получалось

2024-04-16 12:18 UTC, closed without merging